#import "/templates/layout.typ": *

#show: aula.with(
  instrumento: "Modos",
  nivel: "Teoria Musical",
)

#let render-modo(
  nome: "",
  subtitulo: "",
  intervalos: "",
  distancias: "",
  triades: "",
  tetrades: "",
  notas: (),
  ultimo: false,
) = [
  = Modo #nome

  #v(-1em)
  #align(center)[
    #text(size: 14pt, fill: color-secondary, weight: "medium")[
      #subtitulo
    ]
  ]

  #v(0.5em)

  #block(
    fill: luma(248),
    stroke: 0.5pt + luma(200),
    radius: 6pt,
    inset: 1.5em,
    width: 100%,
  )[
    #grid(
      columns: (40%, 60%),
      gutter: 1.5em,
      [
        *Estrutura de Intervalos:* \
        #intervalos

        #v(0.8em)
        *Distâncias:* \
        #distancias
      ],
      [
        *Campo Harmônico (Tríades):* \
        #triades

        #v(0.8em)
        *Campo Harmônico (Tétrades):* \
        #tetrades
      ],
    )
  ]

  #v(1.5em)

  #align(center)[
    #block(
      radius: 4pt,
      stroke: 0.75pt + black,
      clip: true,
      [
        #table(
          columns: (0.5fr, 2fr),
          align: (col, row) => if col == 0 { center + horizon } else { left + horizon },
          inset: (x: 1.5em, y: 0.8em),
          stroke: 0.5pt + black,
          fill: (_, row) => if row == 0 { luma(50) } else if calc.even(row) { luma(240) } else { white },

          [#text(fill: white)[*Tom*]], [#text(fill: white)[*Notas*]],
          ..notas,
        )
      ],
    )
  ]

  #if not ultimo {
    pagebreak()
  }
]

#render-modo(
  nome: "Jônico",
  subtitulo: "I7M da escala Maior",
  intervalos: "T - 2 - 3 - 4 - 5 - 6 - 7M",
  distancias: "T - T - ST - T - T - T - ST",
  triades: "I - IIm - IIIm - IV - V - VIm - VIIº",
  tetrades: "I7M - IIm7 - IIIm7 - IV7M - V7 - VIm7 - VIIø",
  notas: (
    [*C*],
    [C - D - E - F - G - A - B],
    [*Db*],
    [Db - Eb - F - Gb - Ab - Bb - C],
    [*D*],
    [D - E - F\# - G - A - B - C\#],
    [*Eb*],
    [Eb - F - G - Ab - Bb - C - D],
    [*E*],
    [E - F\# - G\# - A - B - C\# - D\#],
    [*F*],
    [F - G - A - Bb - C - D - E],
    [*Gb*],
    [Gb - Ab - Bb - Cb - Db - Eb - F],
    [*G*],
    [G - A - B - C - D - E - F\#],
    [*Ab*],
    [Ab - Bb - C - Db - Eb - F - G],
    [*A*],
    [A - B - C\# - D - E - F\# - G\#],
    [*Bb*],
    [Bb - C - D - Eb - F - G - A],
    [*B*],
    [B - C\# - D\# - E - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Dórico",
  subtitulo: "IIm7 da escala Maior",
  intervalos: "T - 2 - b3 - 4 - 5 - 6 - 7",
  distancias: "T - ST - T - T - T - ST - T",
  triades: "Im - IIm - bIII - IV - Vm - VIº - bVII",
  tetrades: "Im7 - IIm7 - bIII7M - IV7 - Vm7 - VIø - bVII7M",
  notas: (
    [*C*],
    [C - D - Eb - F - G - A - Bb],
    [*C\#*],
    [C\# - D\# - E - F\# - G\# - A\# - B],
    [*D*],
    [D - E - F - G - A - B - C],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A\# - B\# - C\#],
    [*E*],
    [E - F\# - G - A - B - C\# - D],
    [*F*],
    [F - G - Ab - Bb - C - D - Eb],
    [*F\#*],
    [F\# - G\# - A - B - C\# - D\# - E],
    [*G*],
    [G - A - Bb - C - D - E - F],
    [*G\#*],
    [G\# - A\# - B - C\# - D\# - E\# - F\#],
    [*A*],
    [A - B - C - D - E - F\# - G],
    [*Bb*],
    [Bb - C - Db - Eb - F - G - Ab],
    [*B*],
    [B - C\# - D - E - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Frígio",
  subtitulo: "IIIm7 da escala Maior",
  intervalos: "T - b2 - b3 - 4 - 5 - b6 - 7",
  distancias: "ST - T - T - T - ST - T - T",
  triades: "Im - bII - bIII - IVm - Vº - bVI - bVIIm",
  tetrades: "Im7 - bII7M - bIII7 - IVm7 - Vø - bVI7M - bVIIm7",
  notas: (
    [*C*],
    [C - Db - Eb - F - G - Ab - Bb],
    [*C\#*],
    [C\# - D - E - F\# - G\# - A - B],
    [*D*],
    [D - Eb - F - G - A - Bb - C],
    [*D\#*],
    [D\# - E - F\# - G\# - A\# - B - C\#],
    [*E*],
    [E - F - G - A - B - C - D],
    [*F*],
    [F - Gb - Ab - Bb - C - Db - Eb],
    [*F\#*],
    [F\# - G - A - B - C\# - D - E],
    [*G*],
    [G - Ab - Bb - C - D - Eb - F],
    [*G\#*],
    [G\# - A - B - C\# - D\# - E - F\#],
    [*A*],
    [A - Bb - C - D - E - F - G],
    [*Bb*],
    [Bb - Cb - Db - Eb - F - Gb - Ab],
    [*B*],
    [B - C - D - E - F\# - G - A],
  ),
)

#render-modo(
  nome: "Lídio",
  subtitulo: "IV7M da escala Maior",
  intervalos: "T - 2 - 3 - #4 - 5 - 6 - 7M",
  distancias: "T - T - T - ST - T - T - ST",
  triades: "I - II - IIIm - #IVº - V - VIm - VIIm",
  tetrades: "I7M - II7 - IIIm7 - #IVø - V7M - VIm7 - VIIm7",
  notas: (
    [*C*],
    [C - D - E - F\# - G - A - B],
    [*Db*],
    [Db - Eb - F - G - Ab - Bb - C],
    [*D*],
    [D - E - F\# - G\# - A - B - C\#],
    [*Eb*],
    [Eb - F - G - A - Bb - C - D],
    [*E*],
    [E - F\# - G\# - A\# - B - C\# - D\#],
    [*F*],
    [F - G - A - B - C - D - E],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\# - D\# - E\#],
    [*G*],
    [G - A - B - C\# - D - E - F\#],
    [*Ab*],
    [Ab - Bb - C - D - Eb - F - G],
    [*A*],
    [A - B - C\# - D\# - E - F\# - G\#],
    [*Bb*],
    [Bb - C - D - E - F - G - A],
    [*B*],
    [B - C\# - D\# - E\# - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Mixolídio",
  subtitulo: "V7 da escala Maior",
  intervalos: "T - 2 - 3 - 4 - 5 - 6 - 7",
  distancias: "T - T - ST - T - T - ST - T",
  triades: "I - IIm - IIIº - IV - Vm - VIm - bVII",
  tetrades: "I7 - IIm7 - IIIø - IV7M - Vm7 - VIm7 - bVII7M",
  notas: (
    [*C*],
    [C - D - E - F - G - A - Bb],
    [*Db*],
    [Db - Eb - F - Gb - Ab - Bb - Cb],
    [*D*],
    [D - E - F\# - G - A - B - C],
    [*Eb*],
    [Eb - F - G - Ab - Bb - C - Db],
    [*E*],
    [E - F\# - G\# - A - B - C\# - D],
    [*F*],
    [F - G - A - Bb - C - D - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B - C\# - D\# - E],
    [*G*],
    [G - A - B - C - D - E - F],
    [*Ab*],
    [Ab - Bb - C - Db - Eb - F - Gb],
    [*A*],
    [A - B - C\# - D - E - F\# - G],
    [*Bb*],
    [Bb - C - D - Eb - F - G - Ab],
    [*B*],
    [B - C\# - D\# - E - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Eólio",
  subtitulo: "VIm7 da escala Maior",
  intervalos: "T - 2 - b3 - 4 - 5 - b6 - 7",
  distancias: "T - ST - T - T - ST - T - T",
  triades: "Im - IIº - bIII - IVm - Vm - bVI - bVII",
  tetrades: "Im7 - IIø - bIII7M - IVm7 - Vm7 - bVI7M - bVII7",
  notas: (
    [*C*],
    [C - D - Eb - F - G - Ab - Bb],
    [*C\#*],
    [C\# - D\# - E - F\# - G\# - A - B],
    [*D*],
    [D - E - F - G - A - Bb - C],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A\# - B - C\#],
    [*E*],
    [E - F\# - G - A - B - C - D],
    [*F*],
    [F - G - Ab - Bb - C - Db - Eb],
    [*F\#*],
    [F\# - G\# - A - B - C\# - D - E],
    [*G*],
    [G - A - Bb - C - D - Eb - F],
    [*G\#*],
    [G\# - A\# - B - C\# - D\# - E - F\#],
    [*A*],
    [A - B - C - D - E - F - G],
    [*A\#*],
    [A\# - B\# - C\# - D\# - E\# - F\# - G\#],
    [*B*],
    [B - C\# - D - E - F\# - G - A],
  ),
)

#render-modo(
  nome: "Lócrio",
  subtitulo: "VIIø da escala Maior",
  intervalos: "T - b2 - b3 - 4 - b5 - b6 - 7",
  distancias: "ST - T - T - ST - T - T - T",
  triades: "Iº - bII - bIIIm - IVm - bV - bVI - bVIIm",
  tetrades: "Iø - bII7M - bIIIm7 - IVm7 - bV7M - bVI7 - bVIIm7",
  notas: (
    [*C*],
    [C - Db - Eb - F - Gb - Ab - Bb],
    [*C\#*],
    [C\# - D - E - F\# - G - A - B],
    [*D*],
    [D - Eb - F - G - Ab - Bb - C],
    [*D\#*],
    [D\# - E - F\# - G\# - A - B - C\#],
    [*E*],
    [E - F - G - A - Bb - C - D],
    [*F*],
    [F - Gb - Ab - Bb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G - A - B - C - D - E],
    [*G*],
    [G - Ab - Bb - C - Db - Eb - F],
    [*G\#*],
    [G\# - A - B - C\# - D - E - F\#],
    [*A*],
    [A - Bb - C - D - Eb - F - G],
    [*A\#*],
    [A\# - B - C\# - D\# - E - F\# - G\#],
    [*B*],
    [B - C - D - E - F - G - A],
  ),
)

#render-modo(
  nome: "Eólio 7M",
  subtitulo: "Im7M da escala Menor Harmônica",
  intervalos: "T - 2 - b3 - 4 - 5 - b6 - 7M",
  distancias: "T - ST - T - T - ST - 1,5T - ST",
  triades: "Im - IIº - bIII+ - IVm - V - bVI - VIIº",
  tetrades: "Im7M - IIø - bIII7M(#5) - IVm7 - V7 - bVI7M - VIIº7",
  notas: (
    [*C*],
    [C - D - Eb - F - G - Ab - B],
    [*C\#*],
    [C\# - D\# - E - F\# - G\# - A - B\#],
    [*D*],
    [D - E - F - G - A - Bb - C\#],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A\# - B - C\#\#],
    [*E*],
    [E - F\# - G - A - B - C - D\#],
    [*F*],
    [F - G - Ab - Bb - C - Db - E],
    [*F\#*],
    [F\# - G\# - A - B - C\# - D - E\#],
    [*G*],
    [G - A - Bb - C - D - Eb - F\#],
    [*G\#*],
    [G\# - A\# - B - C\# - D\# - E - F\#\#],
    [*A*],
    [A - B - C - D - E - F - G\#],
    [*A\#*],
    [A\# - B\# - C\# - D\# - E\# - F\# - G\#\#],
    [*B*],
    [B - C\# - D - E - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Lócrio 6",
  subtitulo: "IIø da escala Menor Harmônica",
  intervalos: "T - b2 - b3 - 4 - b5 - 6 - 7",
  distancias: "ST - T - T - ST - 1,5T - ST - T",
  triades: "Iº - bII+ - bIIIm - IV - bV - VIº - bVIIm",
  tetrades: "Iø - bII7M(#5) - bIIIm7 - IV7 - bV7M - VIº7 - bVIIm(7M)",
  notas: (
    [*C*],
    [C - Db - Eb - F - Gb - A - Bb],
    [*C\#*],
    [C\# - D - E - F\# - G - A\# - B],
    [*D*],
    [D - Eb - F - G - Ab - B - C],
    [*D\#*],
    [D\# - E - F\# - G\# - A - B\# - C\#],
    [*E*],
    [E - F - G - A - Bb - C\# - D],
    [*F*],
    [F - Gb - Ab - Bb - Cb - D - Eb],
    [*F\#*],
    [F\# - G - A - B - C - D\# - E],
    [*G*],
    [G - Ab - Bb - C - Db - E - F],
    [*G\#*],
    [G\# - A - B - C\# - D - E\# - F\#],
    [*A*],
    [A - Bb - C - D - Eb - F\# - G],
    [*A\#*],
    [A\# - B - C\# - D\# - E - F\#\# - G\#],
    [*B*],
    [B - C - D - E - F - G\# - A],
  ),
)

#render-modo(
  nome: "Jônico #5",
  subtitulo: "bIII7M(#5) da escala Menor Harmônica",
  intervalos: "T - 2 - 3 - 4 - #5 - 6 - 7M",
  distancias: "T - T - ST - 1,5T - ST - T - ST",
  triades: "I+ - IIm - III - IV - #Vº - VIm - VIIº",
  tetrades: "I7M(#5) - IIm7 - III7 - IV7M - #Vº7 - VIm(7M) - VIIø",
  notas: (
    [*C*],
    [C - D - E - F - G\# - A - B],
    [*Db*],
    [Db - Eb - F - Gb - A - Bb - C],
    [*D*],
    [D - E - F\# - G - A\# - B - C\#],
    [*Eb*],
    [Eb - F - G - Ab - B - C - D],
    [*E*],
    [E - F\# - G\# - A - B\# - C\# - D\#],
    [*F*],
    [F - G - A - Bb - C\# - D - E],
    [*Gb*],
    [Gb - Ab - Bb - Cb - D - Eb - F],
    [*G*],
    [G - A - B - C - D\# - E - F\#],
    [*Ab*],
    [Ab - Bb - C - Db - E - F - G],
    [*A*],
    [A - B - C\# - D - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C - D - Eb - F\# - G - A],
    [*B*],
    [B - C\# - D\# - E - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Dórico #4",
  subtitulo: "IVm7 da escala Menor Harmônica",
  intervalos: "T - 2 - b3 - #4 - 5 - 6 - 7",
  distancias: "T - ST - 1,5T - ST - T - ST - T",
  triades: "Im - II - bIII - #IVº - Vm - VIº - bVII+",
  tetrades: "Im7 - II7 - bIII7M - #IVº7 - Vm(7M) - VIø - bVII7M(#5)",
  notas: (
    [*C*],
    [C - D - Eb - F\# - G - A - Bb],
    [*C\#*],
    [C\# - D\# - E - F\#\# - G\# - A\# - B],
    [*D*],
    [D - E - F - G\# - A - B - C],
    [*D\#*],
    [D\# - E\# - F\# - G\#\# - A\# - B\# - C\#],
    [*E*],
    [E - F\# - G - A\# - B - C\# - D],
    [*F*],
    [F - G - Ab - B - C - D - Eb],
    [*F\#*],
    [F\# - G\# - A - B\# - C\# - D\# - E],
    [*G*],
    [G - A - Bb - C\# - D - E - F],
    [*G\#*],
    [G\# - A\# - B - C\#\# - D\# - E\# - F\#],
    [*A*],
    [A - B - C - D\# - E - F\# - G],
    [*Bb*],
    [Bb - C - Db - E - F - G - Ab],
    [*B*],
    [B - C\# - D - E\# - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Mixolídio b9 b6",
  subtitulo: "V7 da escala Menor Harmônica",
  intervalos: "T - b2 - 3 - 4 - 5 - b6 - 7",
  distancias: "ST - 1,5T - ST - T - ST - T - T",
  triades: "I - bII - IIIº - IVm - Vº - bVI+ - bVIIm",
  tetrades: "I7 - bII7M - IIIº7 - IVm(7M) - Vø - bVI7M(#5) - bVIIm7",
  notas: (
    [*C*],
    [C - Db - E - F - G - Ab - Bb],
    [*Db*],
    [Db - Ebb - F - Gb - Ab - Bbb - Cb],
    [*D*],
    [D - Eb - F\# - G - A - Bb - C],
    [*Eb*],
    [Eb - Fb - G - Ab - Bb - Cb - Db],
    [*E*],
    [E - F - G\# - A - B - C - D],
    [*F*],
    [F - Gb - A - Bb - C - Db - Eb],
    [*F\#*],
    [F\# - G - A\# - B - C\# - D - E],
    [*G*],
    [G - Ab - B - C - D - Eb - F],
    [*Ab*],
    [Ab - Bbb - C - Db - Eb - Fb - Gb],
    [*A*],
    [A - Bb - C\# - D - E - F - G],
    [*Bb*],
    [Bb - Cb - D - Eb - F - Gb - Ab],
    [*B*],
    [B - C - D\# - E - F\# - G - A],
  ),
)

#render-modo(
  nome: "Lídio #9",
  subtitulo: "bVI7M da escala Menor Harmônica",
  intervalos: "T - #2 - 3 - #4 - 5 - 6 - 7M",
  distancias: "1,5T - ST - T - ST - T - T - ST",
  triades: "I - #IIº - IIIm - #IVº - V+ - VIm - VII",
  tetrades: "I7M - #IIº7 - IIIm(7M) - #IVø - V7M(#5) - VIm7 - VII7",
  notas: (
    [*C*],
    [C - D\# - E - F\# - G - A - B],
    [*Db*],
    [Db - E - F - G - Ab - Bb - C],
    [*D*],
    [D - E\# - F\# - G\# - A - B - C\#],
    [*Eb*],
    [Eb - F\# - G - A - Bb - C - D],
    [*E*],
    [E - F\#\# - G\# - A\# - B - C\# - D\#],
    [*F*],
    [F - G\# - A - B - C - D - E],
    [*F\#*],
    [F\# - G\#\# - A\# - B\# - C\# - D\# - E\#],
    [*G*],
    [G - A\# - B - C\# - D - E - F\#],
    [*Ab*],
    [Ab - B - C - D - Eb - F - G],
    [*A*],
    [A - B\# - C\# - D\# - E - F\# - G\#],
    [*Bb*],
    [Bb - C\# - D - E - F - G - A],
    [*B*],
    [B - C\#\# - D\# - E\# - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Diminuto Harmônico",
  subtitulo: "VIIº da escala Menor Harmônica",
  intervalos: "T - b2 - b3 - b4 - b5 - b6 - b7",
  distancias: "ST - T - ST - T - T - ST - 1,5T",
  triades: "Iº - bIIm - bIIIº - bIV+ - bVm - bVI - bVII",
  tetrades: "Iº7 - bIIm(7M) - bIIIø - bIV7M(#5) - bVm7 - bVI7 - bVII7M",
  notas: (
    [*C*],
    [C - Db - Eb - Fb - Gb - Ab - Bbb],
    [*C\#*],
    [C\# - D - E - F - G - A - Bb],
    [*D*],
    [D - Eb - F - Gb - Ab - Bb - Cb],
    [*D\#*],
    [D\# - E - F\# - G - A - B - C],
    [*E*],
    [E - F - G - Ab - Bb - C - Db],
    [*F*],
    [F - Gb - Ab - Bbb - Cb - Db - Ebb],
    [*F\#*],
    [F\# - G - A - Bb - C - D - Eb],
    [*G*],
    [G - Ab - Bb - Cb - Db - Eb - Fb],
    [*G\#*],
    [G\# - A - B - C - D - E - F],
    [*A*],
    [A - Bb - C - Db - Eb - F - Gb],
    [*A\#*],
    [A\# - B - C\# - D - E - F\# - G],
    [*B*],
    [B - C - D - Eb - F - G - Ab],
  ),
)

#render-modo(
  nome: "Dórico 7M",
  subtitulo: "Im7M da escala Menor Melódica",
  intervalos: "T - 2 - b3 - 4 - 5 - 6 - 7M",
  distancias: "T - ST - T - T - T - T - ST",
  triades: "Im - IIm - bIII+ - IV - V - VIº - VIIº",
  tetrades: "Im(7M) - IIm7 - bIII7M(#5) - IV7 - V7 - VIø - VIIø",
  notas: (
    [*C*],
    [C - D - Eb - F - G - A - B],
    [*C\#*],
    [C\# - D\# - E - F\# - G\# - A\# - B\#],
    [*D*],
    [D - E - F - G - A - B - C\#],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A\# - B\# - C\#\#],
    [*E*],
    [E - F\# - G - A - B - C\# - D\#],
    [*F*],
    [F - G - Ab - Bb - C - D - E],
    [*F\#*],
    [F\# - G\# - A - B - C\# - D\# - E\#],
    [*G*],
    [G - A - Bb - C - D - E - F\#],
    [*G\#*],
    [G\# - A\# - B - C\# - D\# - E\# - F\#\#],
    [*A*],
    [A - B - C - D - E - F\# - G\#],
    [*Bb*],
    [Bb - C - Db - Eb - F - G - A],
    [*B*],
    [B - C\# - D - E - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Dórico b9",
  subtitulo: "IIm7 da escala Menor Melódica",
  intervalos: "T - b2 - b3 - 4 - 5 - 6 - 7",
  distancias: "ST - T - T - T - T - ST - T",
  triades: "Im - bII+ - bIII - IV - Vº - VIº - bVIIm",
  tetrades: "Im7 - bII7M(#5) - bIII7 - IV7 - Vø - VIø - bVIIm(7M)",
  notas: (
    [*C*],
    [C - Db - Eb - F - G - A - Bb],
    [*C\#*],
    [C\# - D - E - F\# - G\# - A\# - B],
    [*D*],
    [D - Eb - F - G - A - B - C],
    [*D\#*],
    [D\# - E - F\# - G\# - A\# - B\# - C\#],
    [*E*],
    [E - F - G - A - B - C\# - D],
    [*F*],
    [F - Gb - Ab - Bb - C - D - Eb],
    [*F\#*],
    [F\# - G - A - B - C\# - D\# - E],
    [*G*],
    [G - Ab - Bb - C - D - E - F],
    [*G\#*],
    [G\# - A - B - C\# - D\# - E\# - F\#],
    [*A*],
    [A - Bb - C - D - E - F\# - G],
    [*Bb*],
    [Bb - Cb - Db - Eb - F - G - Ab],
    [*B*],
    [B - C - D - E - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Lídio #5",
  subtitulo: "bIII7M(#5) da escala Menor Melódica",
  intervalos: "T - 2 - 3 - #4 - #5 - 6 - 7M",
  distancias: "T - T - T - T - ST - T - ST",
  triades: "I+ - II - III - #IVº - #Vº - VIm - VIIm",
  tetrades: "I7M(#5) - II7 - III7 - #IVø - #Vø - VIm(7M) - VIIm7",
  notas: (
    [*C*],
    [C - D - E - F\# - G\# - A - B],
    [*Db*],
    [Db - Eb - F - G - A - Bb - C],
    [*D*],
    [D - E - F\# - G\# - A\# - B - C\#],
    [*Eb*],
    [Eb - F - G - A - B - C - D],
    [*E*],
    [E - F\# - G\# - A\# - B\# - C\# - D\#],
    [*F*],
    [F - G - A - B - C\# - D - E],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\#\# - D\# - E\#],
    [*G*],
    [G - A - B - C\# - D\# - E - F\#],
    [*Ab*],
    [Ab - Bb - C - D - E - F - G],
    [*A*],
    [A - B - C\# - D\# - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C - D - E - F\# - G - A],
    [*B*],
    [B - C\# - D\# - E\# - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Lídio Dominante",
  subtitulo: "IV7 da escala Menor Melódica",
  intervalos: "T - 2 - 3 - #4 - 5 - 6 - 7",
  distancias: "T - T - T - ST - T - ST - T",
  triades: "I - II - IIIº - #IVº - Vm - VIm - bVII+",
  tetrades: "I7 - II7 - IIIø - #IVø - Vm(7M) - VIm7 - bVII7M(#5)",
  notas: (
    [*C*],
    [C - D - E - F\# - G - A - Bb],
    [*Db*],
    [Db - Eb - F - G - Ab - Bb - Cb],
    [*D*],
    [D - E - F\# - G\# - A - B - C],
    [*Eb*],
    [Eb - F - G - A - Bb - C - Db],
    [*E*],
    [E - F\# - G\# - A\# - B - C\# - D],
    [*F*],
    [F - G - A - B - C - D - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\# - D\# - E],
    [*G*],
    [G - A - B - C\# - D - E - F],
    [*Ab*],
    [Ab - Bb - C - D - Eb - F - Gb],
    [*A*],
    [A - B - C\# - D\# - E - F\# - G],
    [*Bb*],
    [Bb - C - D - E - F - G - Ab],
    [*B*],
    [B - C\# - D\# - E\# - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Mixolídio b6",
  subtitulo: "V7 da escala Menor Melódica",
  intervalos: "T - 2 - 3 - 4 - 5 - b6 - 7",
  distancias: "T - T - ST - T - ST - T - T",
  triades: "I - IIº - IIIº - IVm - Vm - bVI+ - bVII",
  tetrades: "I7 - IIø - IIIø - IVm(7M) - Vm7 - bVI7M(#5) - bVII7",
  notas: (
    [*C*],
    [C - D - E - F - G - Ab - Bb],
    [*Db*],
    [Db - Eb - F - Gb - Ab - Bbb - Cb],
    [*D*],
    [D - E - F\# - G - A - Bb - C],
    [*Eb*],
    [Eb - F - G - Ab - Bb - Cb - Db],
    [*E*],
    [E - F\# - G\# - A - B - C - D],
    [*F*],
    [F - G - A - Bb - C - Db - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B - C\# - D - E],
    [*G*],
    [G - A - B - C - D - Eb - F],
    [*Ab*],
    [Ab - Bb - C - Db - Eb - Fb - Gb],
    [*A*],
    [A - B - C\# - D - E - F - G],
    [*Bb*],
    [Bb - C - D - Eb - F - Gb - Ab],
    [*B*],
    [B - C\# - D\# - E - F\# - G - A],
  ),
)

#render-modo(
  nome: "Lócrio 9",
  subtitulo: "VIø da escala Menor Melódica",
  intervalos: "T - 2 - b3 - 4 - b5 - b6 - 7",
  distancias: "T - ST - T - ST - T - T - T",
  triades: "Iº - IIº - bIIIm - IVm - bV+ - bVI - bVII",
  tetrades: "Iø - IIø - bIIIm(7M) - IVm7 - bV7M(#5) - bVI7 - bVII7",
  notas: (
    [*C*],
    [C - D - Eb - F - Gb - Ab - Bb],
    [*C\#*],
    [C\# - D\# - E - F\# - G - A - B],
    [*D*],
    [D - E - F - G - Ab - Bb - C],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A - B - C\#],
    [*E*],
    [E - F\# - G - A - Bb - C - D],
    [*F*],
    [F - G - Ab - Bb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G\# - A - B - C - D - E],
    [*G*],
    [G - A - Bb - C - Db - Eb - F],
    [*G\#*],
    [G\# - A\# - B - C\# - D - E - F\#],
    [*A*],
    [A - B - C - D - Eb - F - G],
    [*A\#*],
    [A\# - B\# - C\# - D\# - E - F\# - G\#],
    [*B*],
    [B - C\# - D - E - F - G - A],
  ),
)

#render-modo(
  nome: "Alterado",
  subtitulo: "VII7(#5) da escala Menor Melódica",
  intervalos: "T - b2 - #2 - 3 - b5 - #5 - 7",
  distancias: "ST - T - ST - T - T - T - T",
  triades: "Iº - bIIm - bIIIm - bIV+ - bV - bVI - bVIIº",
  tetrades: "Iø - bIIm(7M) - bIIIm7 - bIV7M(#5) - bV7 - bVI7 - bVIIø",
  notas: (
    [*C*],
    [C - Db - D\# - E - Gb - G\# - Bb],
    [*Db*],
    [Db - Ebb - E - F - Abb - A - Cb],
    [*D*],
    [D - Eb - E\# - F\# - Ab - A\# - C],
    [*Eb*],
    [Eb - Fb - F\# - G - Bbb - B - Db],
    [*E*],
    [E - F - F\#\# - G\# - Bb - B\# - D],
    [*F*],
    [F - Gb - G\# - A - Cb - C\# - Eb],
    [*F\#*],
    [F\# - G - G\#\# - A\# - C - C\#\# - E],
    [*G*],
    [G - Ab - A\# - B - Db - D\# - F],
    [*G\#*],
    [G\# - A - A\#\# - B\# - D - D\#\# - F\#],
    [*A*],
    [A - Bb - B\# - C\# - Eb - E\# - G],
    [*Bb*],
    [Bb - Cb - C\# - D - Fb - F\# - Ab],
    [*B*],
    [B - C - C\#\# - D\# - F - F\#\# - A],
  ),
)

#render-modo(
  nome: "Jônico b6",
  subtitulo: "I7M da escala Maior Harmônica",
  intervalos: "T - 2 - 3 - 4 - 5 - b6 - 7M",
  distancias: "T - T - ST - T - ST - 1,5T - ST",
  triades: "I - IIº - IIIm - IVm - V - bVI+ - VIIº",
  tetrades: "I7M - IIø - IIIm7 - IVm(7M) - V7 - bVI7M(#5) - VIIº7",
  notas: (
    [*C*],
    [C - D - E - F - G - Ab - B],
    [*Db*],
    [Db - Eb - F - Gb - Ab - Bbb - C],
    [*D*],
    [D - E - F\# - G - A - Bb - C\#],
    [*Eb*],
    [Eb - F - G - Ab - Bb - Cb - D],
    [*E*],
    [E - F\# - G\# - A - B - C - D\#],
    [*F*],
    [F - G - A - Bb - C - Db - E],
    [*F\#*],
    [F\# - G\# - A\# - B - C\# - D - E\#],
    [*G*],
    [G - A - B - C - D - Eb - F\#],
    [*Ab*],
    [Ab - Bb - C - Db - Eb - Fb - G],
    [*A*],
    [A - B - C\# - D - E - F - G\#],
    [*Bb*],
    [Bb - C - D - Eb - F - Gb - A],
    [*B*],
    [B - C\# - D\# - E - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Lócrio 6/9",
  subtitulo: "IIø da escala Maior Harmônica",
  intervalos: "T - 2 - b3 - 4 - b5 - 6 - 7",
  distancias: "T - ST - T - ST - 1,5T - ST - T",
  triades: "Iº - IIm - bIIIm - IV - bV+ - VIº - bVII",
  tetrades: "Iø - IIm7 - bIIIm(7M) - IV7 - bV7M(#5) - VIº7 - bVII7M",
  notas: (
    [*C*],
    [C - D - Eb - F - Gb - A - Bb],
    [*C\#*],
    [C\# - D\# - E - F\# - G - A\# - B],
    [*D*],
    [D - E - F - G - Ab - B - C],
    [*D\#*],
    [D\# - E\# - F\# - G\# - A - B\# - C\#],
    [*E*],
    [E - F\# - G - A - Bb - C\# - D],
    [*F*],
    [F - G - Ab - Bb - Cb - D - Eb],
    [*F\#*],
    [F\# - G\# - A - B - C - D\# - E],
    [*G*],
    [G - A - Bb - C - Db - E - F],
    [*G\#*],
    [G\# - A\# - B - C\# - D - E\# - F\#],
    [*A*],
    [A - B - C - D - Eb - F\# - G],
    [*A\#*],
    [A\# - B\# - C\# - D\# - E - F\#\# - G\#],
    [*B*],
    [B - C\# - D - E - F - G\# - A],
  ),
)

#render-modo(
  nome: "Frígio b4",
  subtitulo: "IIIm7 da escala Maior Harmônica",
  intervalos: "T - b2 - b3 - b4 - 5 - b6 - 7",
  distancias: "ST - T - ST - 1,5T - ST - T - T",
  triades: "Im - bIIm - bIII - bIV+ - Vº - bVI - bVIIº",
  tetrades: "Im7 - bIIm(7M) - bIII7 - bIV7M(#5) - Vº7 - bVI7M - bVIIø",
  notas: (
    [*C*],
    [C - Db - Eb - Fb - G - Ab - Bb],
    [*C\#*],
    [C\# - D - E - F - G\# - A - B],
    [*D*],
    [D - Eb - F - Gb - A - Bb - C],
    [*D\#*],
    [D\# - E - F\# - G - A\# - B - C\#],
    [*E*],
    [E - F - G - Ab - B - C - D],
    [*F*],
    [F - Gb - Ab - Bbb - C - Db - Eb],
    [*F\#*],
    [F\# - G - A - Bb - C\# - D - E],
    [*G*],
    [G - Ab - Bb - Cb - D - Eb - F],
    [*G\#*],
    [G\# - A - B - C - D\# - E - F\#],
    [*A*],
    [A - Bb - C - Db - E - F - G],
    [*Bb*],
    [Bb - Cb - Db - Ebb - F - Gb - Ab],
    [*B*],
    [B - C - D - Eb - F\# - G - A],
  ),
)

#render-modo(
  nome: "Dórico 7M / #4",
  subtitulo: "IVm7M da escala Maior Harmônica",
  intervalos: "T - 2 - b3 - #4 - 5 - 6 - 7M",
  distancias: "T - ST - 1,5T - ST - T - T - ST",
  triades: "Im - II - bIII+ - #IVº - V - VIº - VIIm",
  tetrades: "Im(7M) - II7 - bIII7M(#5) - #IVº7 - V7M - VIø - VIIm7",
  notas: (
    [*C*],
    [C - D - Eb - F\# - G - A - B],
    [*C\#*],
    [C\# - D\# - E - F\#\# - G\# - A\# - B\#],
    [*D*],
    [D - E - F - G\# - A - B - C\#],
    [*D\#*],
    [D\# - E\# - F\# - G\#\# - A\# - B\# - C\#\#],
    [*E*],
    [E - F\# - G - A\# - B - C\# - D\#],
    [*F*],
    [F - G - Ab - B - C - D - E],
    [*F\#*],
    [F\# - G\# - A - B\# - C\# - D\# - E\#],
    [*G*],
    [G - A - Bb - C\# - D - E - F\#],
    [*G\#*],
    [G\# - A\# - B - C\#\# - D\# - E\# - F\#\#],
    [*A*],
    [A - B - C - D\# - E - F\# - G\#],
    [*Bb*],
    [Bb - C - Db - E - F - G - A],
    [*B*],
    [B - C\# - D - E\# - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Mixolídio b9",
  subtitulo: "V7 da escala Maior Harmônica",
  intervalos: "T - b2 - 3 - 4 - 5 - 6 - 7",
  distancias: "ST - 1,5T - ST - T - T - ST - T",
  triades: "I - bII+ - IIIº - IV - Vº - VIm - bVIIm",
  tetrades: "I7 - bII7M(#5) - IIIº7 - IV7M - Vø - VIm7 - bVIIm(7M)",
  notas: (
    [*C*],
    [C - Db - E - F - G - A - Bb],
    [*Db*],
    [Db - Ebb - F - Gb - Ab - Bb - Cb],
    [*D*],
    [D - Eb - F\# - G - A - B - C],
    [*D\#*],
    [D\# - E - F\#\# - G\# - A\# - B\# - C\#],
    [*Eb*],
    [Eb - Fb - G - Ab - Bb - C - Db],
    [*E*],
    [E - F - G\# - A - B - C\# - D],
    [*F*],
    [F - Gb - A - Bb - C - D - Eb],
    [*F\#*],
    [F\# - G - A\# - B - C\# - D\# - E],
    [*G*],
    [G - Ab - B - C - D - E - F],
    [*Ab*],
    [Ab - Bbb - C - Db - Eb - F - Gb],
    [*A*],
    [A - Bb - C\# - D - E - F\# - G],
    [*Bb*],
    [Bb - Cb - D - Eb - F - G - Ab],
    [*B*],
    [B - C - D\# - E - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Lídio #5 / #9",
  subtitulo: "bVI7M(#5) da escala Maior Harmônica",
  intervalos: "T - #2 - 3 - #4 - #5 - 6 - 7M",
  distancias: "1,5T - ST - T - T - ST - T - ST",
  triades: "I+ - #IIº - III - #IVº - #Vm - VIm - VII",
  tetrades: "I7M(#5) - #IIº7 - III7M - #IVø - #Vm7 - VIm(7M) - VII7",
  notas: (
    [*C*],
    [C - D\# - E - F\# - G\# - A - B],
    [*Db*],
    [Db - E - F - G - A - Bb - C],
    [*D*],
    [D - E\# - F\# - G\# - A\# - B - C\#],
    [*Eb*],
    [Eb - F\# - G - A - B - C - D],
    [*E*],
    [E - F\#\# - G\# - A\# - B\# - C\# - D\#],
    [*F*],
    [F - G\# - A - B - C\# - D - E],
    [*F\#*],
    [F\# - G\#\# - A\# - B\# - C\#\# - D\# - E\#],
    [*G*],
    [G - A\# - B - C\# - D\# - E - F\#],
    [*Ab*],
    [Ab - B - C - D - E - F - G],
    [*A*],
    [A - B\# - C\# - D\# - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C\# - D - E - F\# - G - A],
    [*B*],
    [B - C\#\# - D\# - E\# - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Lócrio b7",
  subtitulo: "VIIº da escala Maior Harmônica",
  intervalos: "T - b2 - b3 - 4 - b5 - b6 - b7",
  distancias: "ST - T - T - ST - T - ST - 1,5T",
  triades: "Iº - bII - bIIIº - IVm - bVm - bVI - bVII(#5)",
  tetrades: "Iº - bII7M - bIIIø - IVm7 - bVm(7M) - bVI7 - bVII7M(#5)",
  notas: (
    [*C*],
    [C - Db - Eb - F - Gb - Ab - Bbb],
    [*C\#*],
    [C\# - D - E - F\# - G - A - Bb],
    [*D*],
    [D - Eb - F - G - Ab - Bb - Cb],
    [*D\#*],
    [D\# - E - F\# - G\# - A - B - C],
    [*E*],
    [E - F - G - A - Bb - C - Db],
    [*F*],
    [F - Gb - Ab - Bb - Cb - Db - Ebb],
    [*F\#*],
    [F\# - G - A - B - C - D - Eb],
    [*G*],
    [G - Ab - Bb - C - Db - Eb - Fb],
    [*G\#*],
    [G\# - A - B - C\# - D - E - F],
    [*A*],
    [A - Bb - C - D - Eb - F - Gb],
    [*A\#*],
    [A\# - B - C\# - D\# - E - F\# - G],
    [*B*],
    [B - C - D - E - F - G - Ab],
  ),
)

#render-modo(
  nome: "Messiaen 1",
  subtitulo: "Escala Hexafônica",
  intervalos: "T - 2 - 3 - #4 - #5 - 7",
  distancias: "T - T - T - T - T - T",
  triades: "I+ - II+ - III+ - #IV+ - #V+ - bVII+",
  tetrades: "I7(#5) - II7(#5) - III7(#5) - #IV7(#5) - #V7(#5) - bVII7(#5)",
  notas: (
    [*C*],
    [C - D - E - F\# - G\# - Bb],
    [*Db*],
    [Db - Eb - F - G - A - Cb],
    [*D*],
    [D - E - F\# - G\# - A\# - C],
    [*Eb*],
    [Eb - F - G - A - B - Db],
    [*E*],
    [E - F\# - G\# - A\# - B\# - D],
    [*F*],
    [F - G - A - B - C\# - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\#\# - E],
    [*G*],
    [G - A - B - C\# - D\# - F],
    [*Ab*],
    [Ab - Bb - C - D - E - Gb],
    [*A*],
    [A - B - C\# - D\# - E\# - G],
    [*Bb*],
    [Bb - C - D - E - F\# - Ab],
    [*B*],
    [B - C\# - D\# - E\# - F\#\# - A],
  ),
)

#render-modo(
  nome: "Messiaen 2",
  subtitulo: "Escala Dominante Diminuta",
  intervalos: "T - b2 - #2 - 3 - #4 - 5 - 6 - 7",
  distancias: "ST - T - ST - T - ST - T - ST - T",
  triades: "I - bIIº - bIII - IIIº - bV - Vº - VI - bVIIº",
  tetrades: "I7 - bIIº7 - bIII7 - IIIº7 - bV7 - Vº7 - VI7 - bVIIº7",
  notas: (
    [*C*],
    [C - Db - D\# - E - F\# - G - A - Bb],
    [*C\#*],
    [C\# - D - D\#\# - E\# - F\#\# - G\# - A\# - B],
    [*D*],
    [D - Eb - E\# - F\# - G\# - A - B - C],
    [*Eb*],
    [Eb - Fb - F\# - G - A - Bb - C - Db],
    [*E*],
    [E - F - F\#\# - G\# - A\# - B - C\# - D],
    [*F*],
    [F - Gb - G\# - A - B - C - D - Eb],
    [*F\#*],
    [F\# - G - G\#\# - A\# - B\# - C\# - D\# - E],
    [*G*],
    [G - Ab - A\# - B - C\# - D - E - F],
    [*Ab*],
    [Ab - Bbb - B - C - D - Eb - F - Gb],
    [*A*],
    [A - Bb - B\# - C\# - D\# - E - F\# - G],
    [*Bb*],
    [Bb - Cb - C\# - D - E - F - G - Ab],
    [*B*],
    [B - C - C\#\# - D\# - E\# - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "Messiaen 3",
  subtitulo: "Escala Tcherepnin",
  intervalos: "T - 2 - b3 - 3 - #4 - 5 - b6 - 7 - 7M",
  distancias: "T - ST - ST - T - ST - ST - T - ST - ST",
  triades: "I - II+ - bIII - III - #IV+ - V - bVI - bVII+ - VII",
  tetrades: "I7M - II+7 - bIII7M - III7M - #IV+7 - V7M - bVI7M - bVII+7 - VII7M",
  notas: (
    [*C*],
    [C - D - Eb - E - F\# - G - Ab - Bb - B],
    [*C\#*],
    [C\# - D\# - E - E\# - F\#\# - G\# - A - B - B\#],
    [*D*],
    [D - E - F - F\# - G\# - A - Bb - C - C\#],
    [*Eb*],
    [Eb - F - Gb - G - A - Bb - Cb - Db - D],
    [*E*],
    [E - F\# - G - G\# - A\# - B - C - D - D\#],
    [*F*],
    [F - G - Ab - A - B - C - Db - Eb - E],
    [*F\#*],
    [F\# - G\# - A - A\# - B\# - C\# - D - E - E\#],
    [*G*],
    [G - A - Bb - B - C\# - D - Eb - F - F\#],
    [*Ab*],
    [Ab - Bb - Cb - C - D - Eb - Fb - Gb - G],
    [*A*],
    [A - B - C - C\# - D\# - E - F - G - G\#],
    [*Bb*],
    [Bb - C - Db - D - E - F - Gb - Ab - A],
    [*B*],
    [B - C\# - D - D\# - E\# - F\# - G - A - A\#],
  ),
)

#render-modo(
  nome: "Messiaen 4",
  subtitulo: "",
  intervalos: "T - b2 - 2 - 4 - #4 - 5 - b6 - 7M",
  distancias: "ST - ST - 1,5T - ST - ST - ST - 1,5T - ST",
  triades: "I - bII - II - IV - #IV - V - bVI - VII",
  tetrades: "I(sus4) - bII7M - IIº7 - IVº7 - #IV(sus4) - V7(b5) - bVIº7 - VIIº7",
  notas: (
    [*C*],
    [C - Db - D - F - F\# - G - Ab - B],
    [*C\#*],
    [C\# - D - D\# - F\# - G - G\# - A - B\#],
    [*D*],
    [D - Eb - E - G - G\# - A - Bb - C\#],
    [*Eb*],
    [Eb - Fb - F - Ab - A - Bb - Cb - D],
    [*E*],
    [E - F - F\# - A - A\# - B - C - D\#],
    [*F*],
    [F - Gb - G - Bb - B - C - Db - E],
    [*F\#*],
    [F\# - G - G\# - B - B\# - C\# - D - E\#],
    [*G*],
    [G - Ab - A - C - C\# - D - Eb - F\#],
    [*Ab*],
    [Ab - Bbb - Bb - Db - D - Eb - Fb - G],
    [*A*],
    [A - Bb - B - D - D\# - E - F - G\#],
    [*Bb*],
    [Bb - Cb - C - Eb - E - F - Gb - A],
    [*B*],
    [B - C - C\# - E - E\# - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Messiaen 5",
  subtitulo: "",
  intervalos: "T - b2 - 4 - #4 - 5 - 7M",
  distancias: "ST - 2T - ST - ST - 2T - ST",
  triades: "I - bII - IV - #IV - V - VII",
  tetrades: "I(sus4) - bII(b5) - IV(sus#4) - #IV(sus4) - V(b5) - VII(b5)",
  notas: (
    [*C*],
    [C - Db - F - F\# - G - B],
    [*C\#*],
    [C\# - D - F\# - F\#\# - G\# - B\#],
    [*D*],
    [D - Eb - G - G\# - A - C\#],
    [*Eb*],
    [Eb - Fb - Ab - A - Bb - D],
    [*E*],
    [E - F - A - A\# - B - D\#],
    [*F*],
    [F - Gb - Bb - B - C - E],
    [*F\#*],
    [F\# - G - B - B\# - C\# - E\#],
    [*G*],
    [G - Ab - C - C\# - D - F\#],
    [*Ab*],
    [Ab - Bbb - Db - D - Eb - G],
    [*A*],
    [A - Bb - D - D\# - E - G\#],
    [*Bb*],
    [Bb - Cb - Eb - E - F - A],
    [*B*],
    [B - C - E - E\# - F\# - A\#],
  ),
)

#render-modo(
  nome: "Messiaen 6",
  subtitulo: "",
  intervalos: "T - 2 - 3 - 4 - #4 - #5 - 7 - 7M",
  distancias: "T - T - ST - ST - T - T - ST - ST",
  triades: "I - II - III - IV - #IV - #V - bVII - VII",
  tetrades: "I7M - II7 - III7 - IV7M - #IV7(b5) - #V7(b5) - bVII7 - VIIº7",
  notas: (
    [*C*],
    [C - D - E - F - F\# - G\# - Bb - B],
    [*C\#*],
    [C\# - D\# - E\# - F\# - F\#\# - G\#\# - B - B\#],
    [*D*],
    [D - E - F\# - G - G\# - A\# - C - C\#],
    [*Eb*],
    [Eb - F - G - Ab - A - B - Db - D],
    [*E*],
    [E - F\# - G\# - A - A\# - B\# - D - D\#],
    [*F*],
    [F - G - A - Bb - B - C\# - Eb - E],
    [*F\#*],
    [F\# - G\# - A\# - B - B\# - C\#\# - E - E\#],
    [*G*],
    [G - A - B - C - C\# - D\# - F - F\#],
    [*Ab*],
    [Ab - Bb - C - Db - D - E - Gb - G],
    [*A*],
    [A - B - C\# - D - D\# - E\# - G - G\#],
    [*Bb*],
    [Bb - C - D - Eb - E - F\# - Ab - A],
    [*B*],
    [B - C\# - D\# - E - E\# - F\#\# - A - A\#],
  ),
)

#render-modo(
  nome: "Messiaen 7",
  subtitulo: "",
  intervalos: "T - b2 - 2 - b3 - 4 - #4 - 5 - b6 - 6 - 7M",
  distancias: "ST - ST - ST - T - ST - ST - ST - ST - T - ST",
  triades: "I - bII - II - bIII - IV - #IV - V - bVI - VI - VII",
  tetrades: "I7M - bII7M - IIº7 - bIII7 - IV7M - #IVº7 - V7 - bVI7 - VIº7 - VIIº7",
  notas: (
    [*C*],
    [C - Db - D - Eb - F - F\# - G - Ab - A - B],
    [*C\#*],
    [C\# - D - D\# - E - F\# - F\#\# - G\# - A - A\# - B\#],
    [*D*],
    [D - Eb - E - F - G - G\# - A - Bb - B - C\#],
    [*Eb*],
    [Eb - Fb - F - Gb - Ab - A - Bb - Cb - C - D],
    [*E*],
    [E - F - F\# - G - A - A\# - B - C - C\# - D\#],
    [*F*],
    [F - Gb - G - Ab - Bb - B - C - Db - D - E],
    [*F\#*],
    [F\# - G - G\# - A - B - B\# - C\# - D - D\# - E\#],
    [*G*],
    [G - Ab - A - Bb - C - C\# - D - Eb - E - F\#],
    [*Ab*],
    [Ab - Bbb - Bb - Cb - Db - D - Eb - Fb - F - G],
    [*A*],
    [A - Bb - B - C - D - D\# - E - F - F\# - G\#],
    [*Bb*],
    [Bb - Cb - C - Db - Eb - E - F - Gb - G - A],
    [*B*],
    [B - C - C\# - D - E - E\# - F\# - G - G\# - A\#],
  ),
)

#render-modo(
  nome: "Duplo Harmônica Maior",
  subtitulo: "I7M da escala Duplo Harmônica Maior",
  intervalos: "T - b2 - 3 - 4 - 5 - b6 - 7M",
  distancias: "ST - 1,5T - ST - T - ST - 1,5T - ST",
  triades: "I - bII - IIIm - IVm - V(b5) - bVI+ - VIIº(bb3)",
  tetrades: "I7M - bII7M - IIIm(b7) - IVm(7M) - V7(b5) - bVI7M(#5) - VIIº7(bb3)",
  notas: (
    [*C*],
    [C - Db - E - F - G - Ab - B],
    [*C\#*],
    [C\# - D - E\# - F\# - G\# - A - B\#],
    [*D*],
    [D - Eb - F\# - G - A - Bb - C\#],
    [*Eb*],
    [Eb - Fb - G - Ab - Bb - Cb - D],
    [*E*],
    [E - F - G\# - A - B - C - D\#],
    [*F*],
    [F - Gb - A - Bb - C - Db - E],
    [*F\#*],
    [F\# - G - A\# - B - C\# - D - E\#],
    [*G*],
    [G - Ab - B - C - D - Eb - F\#],
    [*Ab*],
    [Ab - Bbb - C - Db - Eb - Fb - G],
    [*A*],
    [A - Bb - C\# - D - E - F - G\#],
    [*Bb*],
    [Bb - Cb - D - Eb - F - Gb - A],
    [*B*],
    [B - C - D\# - E - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Lídio #2 #6",
  subtitulo: "bII7M da escala Duplo Harmônica Maior",
  intervalos: "T - #2 - 3 - #4 - 5 - #6 - 7M",
  distancias: "1,5T - ST - T - ST - 1,5T - ST - ST",
  triades: "I - #IIm - IIIm - #IV(b5) - V+ - #VIº(bb3) - VII",
  tetrades: "I7M - #IIm(b7) - IIIm(7M) - #IV7(b5) - V7M(#5) - #VIº7(bb3) - VII7M",
  notas: (
    [*C*],
    [C - D\# - E - F\# - G - A\# - B],
    [*Db*],
    [Db - E - F - G - Ab - B - C],
    [*D*],
    [D - E\# - F\# - G\# - A - B\# - C\#],
    [*Eb*],
    [Eb - F\# - G - A - Bb - C\# - D],
    [*E*],
    [E - F\#\# - G\# - A\# - B - C\#\# - D\#],
    [*F*],
    [F - G\# - A - B - C - D\# - E],
    [*Gb*],
    [Gb - A - Bb - C - Db - E - F],
    [*G*],
    [G - A\# - B - C\# - D - E\# - F\#],
    [*Ab*],
    [Ab - B - C - D - Eb - F\# - G],
    [*A*],
    [A - B\# - C\# - D\# - E - F\#\# - G\#],
    [*Bb*],
    [Bb - C\# - D - E - F - G\# - A],
    [*B*],
    [B - C\#\# - D\# - E\# - F\# - G\#\# - A\#],
  ),
)

#render-modo(
  nome: "Ultrafrígio",
  subtitulo: "IIIm(b7) da escala Duplo Harmônica Maior",
  intervalos: "T - b2 - b3 - b4 - 5 - b6 - b7",
  distancias: "ST - T - ST - 1,5T - ST - ST - 1,5T",
  triades: "Im - bIIm - bIII(b5) - bIV+ - Vº(bb3) - bVI - bbVII",
  tetrades: "Im(b7) - bIIm(7M) - bIII7(b5) - bIV7M(#5) - Vº7(bb3) - bVI7M - bbVII7M",
  notas: (
    [*C*],
    [C - Db - Eb - Fb - G - Ab - Bbb],
    [*C\#*],
    [C\# - D - E - F - G\# - A - Bb],
    [*D*],
    [D - Eb - F - Gb - A - Bb - Cb],
    [*D\#*],
    [D\# - E - F\# - G - A\# - B - C],
    [*E*],
    [E - F - G - Ab - B - C - Db],
    [*F*],
    [F - Gb - Ab - Bbb - C - Db - Ebb],
    [*F\#*],
    [F\# - G - A - Bb - C\# - D - Eb],
    [*G*],
    [G - Ab - Bb - Cb - D - Eb - Fb],
    [*G\#*],
    [G\# - A - B - C - D\# - E - F],
    [*A*],
    [A - Bb - C - Db - E - F - Gb],
    [*A\#*],
    [A\# - B - C\# - D - E\# - F\# - G],
    [*B*],
    [B - C - D - Eb - F\# - G - A],
  ),
)

#render-modo(
  nome: "Menor Húngara",
  subtitulo: "IVm(7M) da escala Duplo Harmônica Maior",
  intervalos: "T - 2 - b3 - #4 - 5 - b6 - 7M",
  distancias: "T - ST - 1,5T - ST - ST - 1,5T - ST",
  triades: "Im - II(b5) - bIII+ - #IVº(bb3) - V - bVI - VIIm",
  tetrades: "Im(7M) - II7(b5) - bIII7M(#5) - #IVº7(bb3) - V7M - bVI7M - VIIm(b7)",
  notas: (
    [*C*],
    [C - D - Eb - F\# - G - Ab - B],
    [*C\#*],
    [C\# - D\# - E - F\#\# - G\# - A - B\#],
    [*D*],
    [D - E - F - G\# - A - Bb - C\#],
    [*Eb*],
    [Eb - F - Gb - A - Bb - Cb - D],
    [*E*],
    [E - F\# - G - A\# - B - C - D\#],
    [*F*],
    [F - G - Ab - B - C - Db - E],
    [*F\#*],
    [F\# - G\# - A - B\# - C\# - D - E\#],
    [*G*],
    [G - A - Bb - C\# - D - Eb - F\#],
    [*Ab*],
    [Ab - Bb - Cb - D - Eb - Fb - G],
    [*A*],
    [A - B - C - D\# - E - F - G\#],
    [*Bb*],
    [Bb - C - Db - E - F - Gb - A],
    [*B*],
    [B - C\# - D - E\# - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Oriental",
  subtitulo: "V7(b5) da escala Duplo Harmônica Maior",
  intervalos: "T - b2 - 3 - 4 - b5 - 6 - 7",
  distancias: "ST - 1,5T - ST - ST - 1,5T - ST - T",
  triades: "I(b5) - bII+ - IIIº(bb3) - IV - bV - VIm - bVIIm",
  tetrades: "I7(b5) - bII7M(#5) - IIIº7(bb3) - IV7M - bV7M - VIm(b7) - bVIIm(7M)",
  notas: (
    [*C*],
    [C - Db - E - F - Gb - A - Bb],
    [*C\#*],
    [C\# - D - E\# - F\# - G - A\# - B],
    [*D*],
    [D - Eb - F\# - G - Ab - B - C],
    [*Eb*],
    [Eb - Fb - G - Ab - Bbb - C - Db],
    [*E*],
    [E - F - G\# - A - Bb - C\# - D],
    [*F*],
    [F - Gb - A - Bb - Cb - D - Eb],
    [*F\#*],
    [F\# - G - A\# - B - C - D\# - E],
    [*G*],
    [G - Ab - B - C - Db - E - F],
    [*G\#*],
    [G\# - A - B\# - C\# - D - E\# - F\#],
    [*A*],
    [A - Bb - C\# - D - Eb - F\# - G],
    [*Bb*],
    [Bb - Cb - D - Eb - Fb - G - Ab],
    [*B*],
    [B - C - D\# - E - F - G\# - A],
  ),
)

#render-modo(
  nome: "Jônico #2 #5",
  subtitulo: "bVI7M(#5) da escala Duplo Harmônica Maior",
  intervalos: "T - #2 - 3 - 4 - #5 - 6 - 7M",
  distancias: "1,5T - ST - ST - 1,5T - ST - T - ST",
  triades: "I+ - #IIº(bb3) - III - IV - #Vm - VIm - VII(b5)",
  tetrades: "I7M(#5) - #IIº7(bb3) - III7M - IV7M - #Vm(b7) - VIm(7M) - VII7(b5)",
  notas: (
    [*C*],
    [C - D\# - E - F - G\# - A - B],
    [*Db*],
    [Db - E - F - Gb - A - Bb - C],
    [*D*],
    [D - E\# - F\# - G - A\# - B - C\#],
    [*Eb*],
    [Eb - F\# - G - Ab - B - C - D],
    [*E*],
    [E - F\#\# - G\# - A - B\# - C\# - D\#],
    [*F*],
    [F - G\# - A - Bb - C\# - D - E],
    [*Gb*],
    [Gb - A - Bb - Cb - D - Eb - F],
    [*G*],
    [G - A\# - B - C - D\# - E - F\#],
    [*Ab*],
    [Ab - B - C - Db - E - F - G],
    [*A*],
    [A - B\# - C\# - D - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C\# - D - Eb - F\# - G - A],
    [*B*],
    [B - C\#\# - D\# - E - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Lócrio bb3 b7",
  subtitulo: "VIIº7(bb3) da escala Duplo Harmônica Maior",
  intervalos: "T - b2 - bb3 - 4 - b5 - b6 - b7",
  distancias: "ST - ST - 1,5T - ST - T - ST - 1,5T",
  triades: "Iº(bb3) - bII - bbIII - IVm - bVm - bVI(b5) - bbVII+",
  tetrades: "Iº7(bb3) - bII7M - bbIII7M - IVm(b7) - bVm(7M) - bVI7(b5) - bbVII7M(#5)",
  notas: (
    [*C*],
    [C - Db - Ebb - F - Gb - Ab - Bbb],
    [*C\#*],
    [C\# - D - Eb - F\# - G - A - Bb],
    [*D*],
    [D - Eb - Fb - G - Ab - Bb - Cb],
    [*D\#*],
    [D\# - E - F - G\# - A - B - C],
    [*E*],
    [E - F - Gb - A - Bb - C - Db],
    [*F*],
    [F - Gb - Abb - Bb - Cb - Db - Ebb],
    [*F\#*],
    [F\# - G - Ab - B - C - D - Eb],
    [*G*],
    [G - Ab - Bbb - C - Db - Eb - Fb],
    [*G\#*],
    [G\# - A - Bb - C\# - D - E - F],
    [*A*],
    [A - Bb - Cb - D - Eb - F - Gb],
    [*A\#*],
    [A\# - B - C - D\# - E - F\# - G],
    [*B*],
    [B - C - Db - E - F - G - Ab],
  ),
)

#render-modo(
  nome: "Napolitana Maior",
  subtitulo: "Im(7M) da escala Napolitana Maior",
  intervalos: "T - b2 - b3 - 4 - 5 - 6 - 7M",
  distancias: "ST - T - T - T - T - T - ST",
  triades: "Im - bII+ - bIII+ - IV - V(b5) - VIº - VIIº(bb3)",
  tetrades: "Im(7M) - bII7M(#5) - bIII7(#5) - IV7 - V7(b5) - VIø - VIIø(bb3)",
  notas: (
    [*C*],
    [C - Db - Eb - F - G - A - B],
    [*Db*],
    [Db - Ebb - Fb - Gb - Ab - Bb - C],
    [*D*],
    [D - Eb - F - G - A - B - C\#],
    [*Eb*],
    [Eb - Fb - Gb - Ab - Bb - C - D],
    [*E*],
    [E - F - G - A - B - C\# - D\#],
    [*F*],
    [F - Gb - Ab - Bb - C - D - E],
    [*F\#*],
    [F\# - G - A - B - C\# - D\# - E\#],
    [*G*],
    [G - Ab - Bb - C - D - E - F\#],
    [*Ab*],
    [Ab - Bbb - Cb - Db - Eb - F - G],
    [*A*],
    [A - Bb - C - D - E - F\# - G\#],
    [*Bb*],
    [Bb - Cb - Db - Eb - F - G - A],
    [*B*],
    [B - C - D - E - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Lídio #5 #6",
  subtitulo: "bII7M(#5) da escala Napolitana Maior",
  intervalos: "T - 2 - 3 - #4 - #5 - #6 - 7M",
  distancias: "T - T - T - T - T - ST - ST",
  triades: "I+ - II+ - III - #IV(b5) - #Vº - #VIº(bb3) - VIIm",
  tetrades: "I7M(#5) - II7(#5) - III7 - #IV7(b5) - #Vø - #VIø(bb3) - VIIm(7M)",
  notas: (
    [*C*],
    [C - D - E - F\# - G\# - A\# - B],
    [*Db*],
    [Db - Eb - F - G - A - B - C],
    [*D*],
    [D - E - F\# - G\# - A\# - B\# - C\#],
    [*Eb*],
    [Eb - F - G - A - B - C\# - D],
    [*E*],
    [E - F\# - G\# - A\# - B\# - C\#\# - D\#],
    [*F*],
    [F - G - A - B - C\# - D\# - E],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\#\# - D\#\# - E\#],
    [*G*],
    [G - A - B - C\# - D\# - E\# - F\#],
    [*Ab*],
    [Ab - Bb - C - D - E - F\# - G],
    [*A*],
    [A - B - C\# - D\# - E\# - F\#\# - G\#],
    [*Bb*],
    [Bb - C - D - E - F\# - G\# - A],
    [*B*],
    [B - C\# - D\# - E\# - F\#\# - G\#\# - A\#],
  ),
)

#render-modo(
  nome: "Mixolídio #4 #5",
  subtitulo: "bIII7(#5) da escala Napolitana Maior",
  intervalos: "T - 2 - 3 - #4 - #5 - 6 - 7",
  distancias: "T - T - T - T - ST - ST - T",
  triades: "I+ - II - III(b5) - #IVº - #Vº(bb3) - VIm - bVII+",
  tetrades: "I7(#5) - II7 - III7(b5) - #IVø - #Vø(bb3) - VIm(7M) - bVII7M(#5)",
  notas: (
    [*C*],
    [C - D - E - F\# - G\# - A - Bb],
    [*Db*],
    [Db - Eb - F - G - A - Bb - Cb],
    [*D*],
    [D - E - F\# - G\# - A\# - B - C],
    [*Eb*],
    [Eb - F - G - A - B - C - Db],
    [*E*],
    [E - F\# - G\# - A\# - B\# - C\# - D],
    [*F*],
    [F - G - A - B - C\# - D - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\#\# - D\# - E],
    [*G*],
    [G - A - B - C\# - D\# - E - F],
    [*Ab*],
    [Ab - Bb - C - D - E - F - Gb],
    [*A*],
    [A - B - C\# - D\# - E\# - F\# - G],
    [*Bb*],
    [Bb - C - D - E - F\# - G - Ab],
    [*B*],
    [B - C\# - D\# - E\# - F\#\# - G\# - A],
  ),
)

#render-modo(
  nome: "Lídio b6",
  subtitulo: "IV7 da escala Napolitana Maior",
  intervalos: "T - 2 - 3 - #4 - 5 - b6 - 7",
  distancias: "T - T - T - ST - ST - T - T",
  triades: "I - II(b5) - IIIº - #IVº(bb3) - Vm - bVI+ - bVII+",
  tetrades: "I7 - II7(b5) - IIIø - #IVø(bb3) - Vm(7M) - bVI7M(#5) - bVII7(#5)",
  notas: (
    [*C*],
    [C - D - E - F\# - G - Ab - Bb],
    [*Db*],
    [Db - Eb - F - G - Ab - Bbb - Cb],
    [*D*],
    [D - E - F\# - G\# - A - Bb - C],
    [*Eb*],
    [Eb - F - G - A - Bb - Cb - Db],
    [*E*],
    [E - F\# - G\# - A\# - B - C - D],
    [*F*],
    [F - G - A - B - C - Db - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\# - D - E],
    [*G*],
    [G - A - B - C\# - D - Eb - F],
    [*Ab*],
    [Ab - Bb - C - D - Eb - Fb - Gb],
    [*A*],
    [A - B - C\# - D\# - E - F - G],
    [*Bb*],
    [Bb - C - D - E - F - Gb - Ab],
    [*B*],
    [B - C\# - D\# - E\# - F\# - G - A],
  ),
)

#render-modo(
  nome: "Mixolídio b5 b6",
  subtitulo: "V7(b5) da escala Napolitana Maior",
  intervalos: "T - 2 - 3 - 4 - b5 - b6 - 7",
  distancias: "T - T - ST - ST - T - T - T",
  triades: "I(b5) - IIº - IIIº(bb3) - IVm - bV+ - bVI+ - bVII",
  tetrades: "I7(b5) - IIø - IIIø(bb3) - IVm(7M) - bV7M(#5) - bVI7(#5) - bVII7",
  notas: (
    [*C*],
    [C - D - E - F - Gb - Ab - Bb],
    [*Db*],
    [Db - Eb - F - Gb - Abb - Bbb - Cb],
    [*D*],
    [D - E - F\# - G - Ab - Bb - C],
    [*Eb*],
    [Eb - F - G - Ab - Bbb - Cb - Db],
    [*E*],
    [E - F\# - G\# - A - Bb - C - D],
    [*F*],
    [F - G - A - Bb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B - C - D - E],
    [*G*],
    [G - A - B - C - Db - Eb - F],
    [*Ab*],
    [Ab - Bb - C - Db - Ebb - Fb - Gb],
    [*A*],
    [A - B - C\# - D - Eb - F - G],
    [*Bb*],
    [Bb - C - D - Eb - Fb - Gb - Ab],
    [*B*],
    [B - C\# - D\# - E - F - G - A],
  ),
)

#render-modo(
  nome: "Eólio b4",
  subtitulo: "VIø da escala Napolitana Maior",
  intervalos: "T - 2 - b3 - b4 - b5 - b6 - 7",
  distancias: "T - ST - ST - T - T - T - ST",
  triades: "Iº - IIº(bb3) - bIIIm - bIV+ - bV+ - bVI - bVII(b5)",
  tetrades: "Iø - IIø(bb3) - bIIIm(7M) - bIV7M(#5) - bV7(#5) - bVI7 - bVII7(b5)",
  notas: (
    [*C*],
    [C - D - Eb - Fb - Gb - Ab - Bb],
    [*Db*],
    [Db - Eb - Fb - Gbb - Abb - Bbb - Cb],
    [*D*],
    [D - E - F - Gb - Ab - Bb - C],
    [*Eb*],
    [Eb - F - Gb - Abb - Bbb - Cb - Db],
    [*E*],
    [E - F\# - G - Ab - Bb - C - D],
    [*F*],
    [F - G - Ab - Bbb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G\# - A - Bb - C - D - E],
    [*G*],
    [G - A - Bb - Cb - Db - Eb - F],
    [*Ab*],
    [Ab - Bb - Cb - Dbb - Ebb - Fb - Gb],
    [*A*],
    [A - B - C - Db - Eb - F - G],
    [*Bb*],
    [Bb - C - Db - Ebb - Fb - Gb - Ab],
    [*B*],
    [B - C\# - D - Eb - F - G - A],
  ),
)

#render-modo(
  nome: "Super Lócrio bb3",
  subtitulo: "VIIø(bb3) da escala Napolitana Maior",
  intervalos: "T - b2 - bb3 - b4 - b5 - b6 - 7",
  distancias: "ST - ST - T - T - T - ST - T",
  triades: "Iº(bb3) - bIIm - bbIII+ - bIV+ - bV - bVI(b5) - bVIIº",
  tetrades: "Iø(bb3) - bIIm(7M) - bbIII7M(#5) - bIV7(#5) - bV7 - bVI7(b5) - bVIIø",
  notas: (
    [*C*],
    [C - Db - Ebb - Fb - Gb - Ab - Bb],
    [*Db*],
    [Db - Ebb - Fbb - Gbb - Abb - Bbb - Cb],
    [*D*],
    [D - Eb - Fb - Gb - Ab - Bb - C],
    [*Eb*],
    [Eb - Fb - Gbb - Abb - Bbb - Cb - Db],
    [*E*],
    [E - F - Gb - Ab - Bb - C - D],
    [*F*],
    [F - Gb - Abb - Bbb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G - Ab - Bb - C - D - E],
    [*G*],
    [G - Ab - Bbb - Cb - Db - Eb - F],
    [*Ab*],
    [Ab - Bbb - Cbb - Dbb - Ebb - Fb - Gb],
    [*A*],
    [A - Bb - Cb - Db - Eb - F - G],
    [*Bb*],
    [Bb - Cb - Dbb - Ebb - Fb - Gb - Ab],
    [*B*],
    [B - C - Db - Eb - F - G - A],
  ),
  ultimo: true,
)

#render-modo(
  nome: "Napolitana Menor",
  subtitulo: "Im(7M) da escala Napolitana Menor",
  intervalos: "T - b2 - b3 - 4 - 5 - b6 - 7M",
  distancias: "ST - T - T - T - ST - 1,5T - ST",
  triades: "Im - bII - bIII+ - IVm - V(b5) - bVI - VIIº(bb3)",
  tetrades: "Im(7M) - bII7M - bIII7M(#5) - IVm7 - V7(b5) - bVI7M - VIIº7(bb3)",
  notas: (
    [*C*],
    [C - Db - Eb - F - G - Ab - B],
    [*Db*],
    [Db - Ebb - Fb - Gb - Ab - Bbb - C],
    [*D*],
    [D - Eb - F - G - A - Bb - C\#],
    [*Eb*],
    [Eb - Fb - Gb - Ab - Bb - Cb - D],
    [*E*],
    [E - F - G - A - B - C - D\#],
    [*F*],
    [F - Gb - Ab - Bb - C - Db - E],
    [*F\#*],
    [F\# - G - A - B - C\# - D - E\#],
    [*G*],
    [G - Ab - Bb - C - D - Eb - F\#],
    [*Ab*],
    [Ab - Bbb - Cb - Db - Eb - Fb - G],
    [*A*],
    [A - Bb - C - D - E - F - G\#],
    [*Bb*],
    [Bb - Cb - Db - Eb - F - Gb - A],
    [*B*],
    [B - C - D - E - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "Lídio #6",
  subtitulo: "bII7M da escala Napolitana Menor",
  intervalos: "T - 2 - 3 - #4 - 5 - #6 - 7M",
  distancias: "T - T - T - ST - 1,5T - ST - ST",
  triades: "I - II+ - IIIm - #IV(b5) - V - #VIº(bb3) - VIIm",
  tetrades: "I7M - II7(#5) - IIIm7 - #IV7(b5) - V7M - #VIº7(bb3) - VIIm(7M)",
  notas: (
    [*C*],
    [C - D - E - F\# - G - A\# - B],
    [*Db*],
    [Db - Eb - F - G - Ab - B - C],
    [*D*],
    [D - E - F\# - G\# - A - B\# - C\#],
    [*Eb*],
    [Eb - F - G - A - Bb - C\# - D],
    [*E*],
    [E - F\# - G\# - A\# - B - C\#\# - D\#],
    [*F*],
    [F - G - A - B - C - D\# - E],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\# - D\#\# - E\#],
    [*G*],
    [G - A - B - C\# - D - E\# - F\#],
    [*Ab*],
    [Ab - Bb - C - D - Eb - F\# - G],
    [*A*],
    [A - B - C\# - D\# - E - F\#\# - G\#],
    [*Bb*],
    [Bb - C - D - E - F - G\# - A],
    [*B*],
    [B - C\# - D\# - E\# - F\# - G\#\# - A\#],
  ),
)

#render-modo(
  nome: "Mixolídio #5",
  subtitulo: "bIII7M(#5) da escala Napolitana Menor",
  intervalos: "T - 2 - 3 - 4 - #5 - 6 - 7",
  distancias: "T - T - ST - 1,5T - ST - ST - T",
  triades: "I+ - IIm - III(b5) - IV - #Vº(bb3) - VIm - bVII",
  tetrades: "I7(#5) - IIm7 - III7(b5) - IV7M - #Vº7(bb3) - VIm(7M) - bVII7M",
  notas: (
    [*C*],
    [C - D - E - F - G\# - A - Bb],
    [*Db*],
    [Db - Eb - F - Gb - A - Bb - Cb],
    [*D*],
    [D - E - F\# - G - A\# - B - C],
    [*Eb*],
    [Eb - F - G - Ab - B - C - Db],
    [*E*],
    [E - F\# - G\# - A - B\# - C\# - D],
    [*F*],
    [F - G - A - Bb - C\# - D - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B - C\#\# - D\# - E],
    [*G*],
    [G - A - B - C - D\# - E - F],
    [*Ab*],
    [Ab - Bb - C - Db - E - F - Gb],
    [*A*],
    [A - B - C\# - D - E\# - F\# - G],
    [*Bb*],
    [Bb - C - D - Eb - F\# - G - Ab],
    [*B*],
    [B - C\# - D\# - E - F\#\# - G\# - A],
  ),
)

#render-modo(
  nome: "Romani Menor",
  subtitulo: "IVm7 da escala Napolitana Menor",
  intervalos: "T - 2 - b3 - #4 - 5 - b6 - 7",
  distancias: "T - ST - 1,5T - ST - ST - T - T",
  triades: "Im - II(b5) - bIII - #IVº(bb3) - Vm - bVI - bVII+",
  tetrades: "Im7 - II7(b5) - bIII7M - #IVº7(bb3) - Vm(7M) - bVI7M - bVII7(#5)",
  notas: (
    [*C*],
    [C - D - Eb - F\# - G - Ab - Bb],
    [*Db*],
    [Db - Eb - Fb - G - Ab - Bbb - Cb],
    [*D*],
    [D - E - F - G\# - A - Bb - C],
    [*Eb*],
    [Eb - F - Gb - A - Bb - Cb - Db],
    [*E*],
    [E - F\# - G - A\# - B - C - D],
    [*F*],
    [F - G - Ab - B - C - Db - Eb],
    [*F\#*],
    [F\# - G\# - A - B\# - C\# - D - E],
    [*G*],
    [G - A - Bb - C\# - D - Eb - F],
    [*Ab*],
    [Ab - Bb - Cb - D - Eb - Fb - Gb],
    [*A*],
    [A - B - C - D\# - E - F - G],
    [*Bb*],
    [Bb - C - Db - E - F - Gb - Ab],
    [*B*],
    [B - C\# - D - E\# - F\# - G - A],
  ),
)

#render-modo(
  nome: "Lócrio Maior",
  subtitulo: "V7(b5) da escala Napolitana Menor",
  intervalos: "T - b2 - 3 - 4 - b5 - b6 - 7",
  distancias: "ST - 1,5T - ST - ST - T - T - T",
  triades: "I(b5) - bII - IIIº(bb3) - IVm - bV - bVI+ - bVIIm",
  tetrades: "I7(b5) - bII7M - IIIº7(bb3) - IVm(7M) - bV7M - bVI7(#5) - bVIIm7",
  notas: (
    [*C*],
    [C - Db - E - F - Gb - Ab - Bb],
    [*Db*],
    [Db - Ebb - F - Gb - Abb - Bbb - Cb],
    [*D*],
    [D - Eb - F\# - G - Ab - Bb - C],
    [*Eb*],
    [Eb - Fb - G - Ab - Bbb - Cb - Db],
    [*E*],
    [E - F - G\# - A - Bb - C - D],
    [*F*],
    [F - Gb - A - Bb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G - A\# - B - C - D - E],
    [*G*],
    [G - Ab - B - C - Db - Eb - F],
    [*Ab*],
    [Ab - Bbb - C - Db - Ebb - Fb - Gb],
    [*A*],
    [A - Bb - C\# - D - Eb - F - G],
    [*Bb*],
    [Bb - Cb - D - Eb - Fb - Gb - Ab],
    [*B*],
    [B - C - D\# - E - F - G - A],
  ),
)

#render-modo(
  nome: "Jônico #2",
  subtitulo: "bVI7M da escala Napolitana Menor",
  intervalos: "T - #2 - 3 - 4 - 5 - 6 - 7M",
  distancias: "1,5T - ST - ST - T - T - T - ST",
  triades: "I - #IIº(bb3) - IIIm - IV - V+ - VIm - VII(b5)",
  tetrades: "I7M - #IIº7(bb3) - IIIm(7M) - IV7M - V7(#5) - VIm7 - VII7(b5)",
  notas: (
    [*C*],
    [C - D\# - E - F - G - A - B],
    [*Db*],
    [Db - E - F - Gb - Ab - Bb - C],
    [*D*],
    [D - E\# - F\# - G - A - B - C\#],
    [*Eb*],
    [Eb - F\# - G - Ab - Bb - C - D],
    [*E*],
    [E - F\#\# - G\# - A - B - C\# - D\#],
    [*F*],
    [F - G\# - A - Bb - C - D - E],
    [*F\#*],
    [F\# - G\#\# - A\# - B - C\# - D\# - E\#],
    [*G*],
    [G - A\# - B - C - D - E - F\#],
    [*Ab*],
    [Ab - B - C - Db - Eb - F - G],
    [*A*],
    [A - B\# - C\# - D - E - F\# - G\#],
    [*Bb*],
    [Bb - C\# - D - Eb - F - G - A],
    [*B*],
    [B - C\#\# - D\# - E - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Ultralócrio",
  subtitulo: "VIIº7(bb3) da escala Napolitana Menor",
  intervalos: "T - b2 - bb3 - b4 - b5 - b6 - b7",
  distancias: "ST - ST - T - T - T - ST - 1,5T",
  triades: "Iº(bb3) - bIIm - bbIII - bIV+ - bVm - bVI(b5) - bbVII",
  tetrades: "Iº7(bb3) - bIIm(7M) - bbIII7M - bIV7(#5) - bVm7 - bVI7(b5) - bbVII7M",
  notas: (
    [*C*],
    [C - Db - Ebb - Fb - Gb - Ab - Bbb],
    [*Db*],
    [Db - Ebb - Fbb - Gbb - Abb - Bbb - Cbb],
    [*D*],
    [D - Eb - Fb - Gb - Ab - Bb - Cb],
    [*Eb*],
    [Eb - Fb - Gbb - Abb - Bbb - Cb - Dbb],
    [*E*],
    [E - F - Gb - Ab - Bb - C - Db],
    [*F*],
    [F - Gb - Abb - Bbb - Cb - Db - Ebb],
    [*F\#*],
    [F\# - G - Ab - Bb - C - D - Eb],
    [*G*],
    [G - Ab - Bbb - Cb - Db - Eb - Fb],
    [*Ab*],
    [Ab - Bbb - Cbb - Dbb - Ebb - Fb - Gbb],
    [*A*],
    [A - Bb - Cb - Db - Eb - F - Gb],
    [*Bb*],
    [Bb - Cb - Dbb - Ebb - Fb - Gb - Abb],
    [*B*],
    [B - C - Db - Eb - F - G - Ab],
  ),
)

#render-modo(
  nome: "Maior Húngara",
  subtitulo: "I7 da escala Maior Húngara",
  intervalos: "T - #2 - 3 - #4 - 5 - 6 - 7",
  distancias: "1,5T - ST - T - ST - T - ST - T",
  triades: "I - #IIº(bb3) - IIIº - #IVº - Vm(#5) - VIm - bVII(##3, #5)",
  tetrades: "I7 - #IIº7(bb3) - IIIº(7M) - #IVø - Vm(7M, #5) - VIm7 - bVII7(##3, #5)",
  notas: (
    [*C*],
    [C - D\# - E - F\# - G - A - Bb],
    [*Db*],
    [Db - E - F - G - Ab - Bb - Cb],
    [*D*],
    [D - E\# - F\# - G\# - A - B - C],
    [*Eb*],
    [Eb - F\# - G - A - Bb - C - Db],
    [*E*],
    [E - F\#\# - G\# - A\# - B - C\# - D],
    [*F*],
    [F - G\# - A - B - C - D - Eb],
    [*F\#*],
    [F\# - G\#\# - A\# - B\# - C\# - D\# - E],
    [*G*],
    [G - A\# - B - C\# - D - E - F],
    [*Ab*],
    [Ab - B - C - D - Eb - F - Gb],
    [*A*],
    [A - B\# - C\# - D\# - E - F\# - G],
    [*Bb*],
    [Bb - C\# - D - E - F - G - Ab],
    [*B*],
    [B - C\#\# - D\# - E\# - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "2 Maior Húngara",
  subtitulo: "#IIm7(b5) da escala Maior Húngara",
  intervalos: "T - b2 - b3 - b4 - b5 - bb6 - bb7",
  distancias: "ST - T - ST - T - ST - T - 1,5T",
  triades: "Im - bIIº - bIIIº - bIVm(#5) - bVm - bbVI(##3, #5) - bbVII",
  tetrades: "Im(b7) - bIIø - bIIIº(7M) - bIVm(7M, #5) - bVm7 - bbVI7(##3, #5) - bbVII7",
  notas: (
    [*C*],
    [C - Db - Eb - Fb - Gb - Abb - Bbb],
    [*C\#*],
    [C\# - D - E - F - G - Ab - Bb],
    [*D*],
    [D - Eb - F - Gb - Ab - Bbb - Cb],
    [*D\#*],
    [D\# - E - F\# - G - A - Bb - C],
    [*E*],
    [E - F - G - Ab - Bb - Cb - Db],
    [*F*],
    [F - Gb - Ab - Bbb - Cb - Dbb - Ebb],
    [*F\#*],
    [F\# - G - A - Bb - C - Db - Eb],
    [*G*],
    [G - Ab - Bb - Cb - Db - Ebb - Fb],
    [*G\#*],
    [G\# - A - B - C - D - Eb - F],
    [*A*],
    [A - Bb - C - Db - Eb - Fb - Gb],
    [*A\#*],
    [A\# - B - C\# - D - E - F - G],
    [*B*],
    [B - C - D - Eb - F - Gb - Ab],
  ),
)

#render-modo(
  nome: "3 Maior Húngara",
  subtitulo: "IIIº(7M) da escala Maior Húngara",
  intervalos: "T - 2 - b3 - 4 - b5 - b6 - 7M",
  distancias: "T - ST - T - ST - T - 1,5T - ST",
  triades: "Iº - IIº - IIIm(#5) - IVm - bV(##3, #5) - bVI - VII",
  tetrades: "Iº(7M) - IIº7 - IIIm(7M, #5) - IVm7 - bV7(##3, #5) - bVI7 - VII7M",
  notas: (
    [*C*],
    [C - D - Eb - F - Gb - Ab - B],
    [*C\#*],
    [C\# - D\# - E - F\# - G - A - B\#],
    [*D*],
    [D - E - F - G - Ab - Bb - C\#],
    [*Eb*],
    [Eb - F - Gb - Ab - Bbb - Cb - D],
    [*E*],
    [E - F\# - G - A - Bb - C - D\#],
    [*F*],
    [F - G - Ab - Bb - Cb - Db - E],
    [*F\#*],
    [F\# - G\# - A - B - C - D - E\#],
    [*G*],
    [G - A - Bb - C - Db - Eb - F\#],
    [*Ab*],
    [Ab - Bb - Cb - Db - Ebb - Fb - G],
    [*A*],
    [A - B - C - D - Eb - F - G\#],
    [*Bb*],
    [Bb - C - Db - Eb - Fb - Gb - A],
    [*B*],
    [B - C\# - D - E - F - G - A\#],
  ),
)

#render-modo(
  nome: "4 Maior Húngara",
  subtitulo: "#IVm7(b5) da escala Maior Húngara",
  intervalos: "T - b2 - b3 - bb4 - b5 - 6 - 7",
  distancias: "ST - T - ST - T - 1,5T - ST - T",
  triades: "Iº - IIm(#5) - bIIIm - bIV(##3, #5) - bV - VI - bVIIº",
  tetrades: "Iø - IIm(7M, #5) - bIIIm7 - bIV7(##3, #5) - bV7 - VI7 - bVIIø",
  notas: (
    [*C*],
    [C - Db - Eb - Fb - Gb - A - Bb],
    [*C\#*],
    [C\# - D - E - F - G - A\# - B],
    [*D*],
    [D - Eb - F - Gb - Ab - B - C],
    [*D\#*],
    [D\# - E - F\# - G - A - B\# - C\#],
    [*E*],
    [E - F - G - Ab - Bb - C\# - D],
    [*F*],
    [F - Gb - Ab - Bbb - Cb - D - Eb],
    [*F\#*],
    [F\# - G - A - Bb - C - D\# - E],
    [*G*],
    [G - Ab - Bb - Cb - Db - E - F],
    [*G\#*],
    [G\# - A - B - C - D - E\# - F\#],
    [*A*],
    [A - Bb - C - Db - Eb - F\# - G],
    [*A\#*],
    [A\# - B - C\# - D - E - F\#\# - G\#],
    [*B*],
    [B - C - D - Eb - F - G\# - A],
  ),
)

#render-modo(
  nome: "5 Maior Húngara",
  subtitulo: "Vm(7M, #5) da escala Maior Húngara",
  intervalos: "T - 2 - b3 - 4 - #5 - 6 - 7M",
  distancias: "T - ST - T - 1,5T - ST - T - ST",
  triades: "Im(#5) - IIm - bIII(##3, #5) - IV - V - VIº - VIIº",
  tetrades: "Im(7M, #5) - IIm7 - bIII7(##3, #5) - IV7 - V7 - VIø - VIIº(7M)",
  notas: (
    [*C*],
    [C - D - Eb - F - G\# - A - B],
    [*C\#*],
    [C\# - D\# - E - F\# - A - A\# - B\#],
    [*D*],
    [D - E - F - G - A\# - B - C\#],
    [*Eb*],
    [Eb - F - Gb - Ab - B - C - D],
    [*E*],
    [E - F\# - G - A - B\# - C\# - D\#],
    [*F*],
    [F - G - Ab - Bb - C\# - D - E],
    [*F\#*],
    [F\# - G\# - A - B - D - D\# - E\#],
    [*G*],
    [G - A - Bb - C - D\# - E - F\#],
    [*Ab*],
    [Ab - Bb - Cb - Db - E - F - G],
    [*A*],
    [A - B - C - D - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C - Db - Eb - F\# - G - A],
    [*B*],
    [B - C\# - D - E - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "6 Maior Húngara",
  subtitulo: "VIm7 da escala Maior Húngara",
  intervalos: "T - b2 - b3 - #4 - 5 - 6 - 7",
  distancias: "ST - T - 1,5T - ST - T - T - ST",
  triades: "Im - bII(##3, #5) - bIII - #IV - Vº - VIº - bVIIm(#5)",
  tetrades: "Im7 - bII7(##3, #5) - bIII7M - #IV7 - Vø - VIº(7M) - bVIIm(7M, #5)",
  notas: (
    [*C*],
    [C - Db - Eb - F\# - G - A - Bb],
    [*C\#*],
    [C\# - D - E - F\#\# - G\# - A\# - B],
    [*D*],
    [D - Eb - F - G\# - A - B - C],
    [*Eb*],
    [Eb - Fb - Gb - A - Bb - C - Db],
    [*E*],
    [E - F - G - A\# - B - C\# - D],
    [*F*],
    [F - Gb - Ab - B - C - D - Eb],
    [*F\#*],
    [F\# - G - A - B\# - C\# - D\# - E],
    [*G*],
    [G - Ab - Bb - C\# - D - E - F],
    [*Ab*],
    [Ab - Bbb - Cb - D - Eb - F - Gb],
    [*A*],
    [A - Bb - C - D\# - E - F\# - G],
    [*Bb*],
    [Bb - Cb - Db - E - F - G - Ab],
    [*B*],
    [B - C - D - E\# - F\# - G\# - A],
  ),
)

#render-modo(
  nome: "7 Maior Húngara",
  subtitulo: "bVII7(##3, #5) da escala Maior Húngara",
  intervalos: "T - 2 - #3 - #4 - #5 - 6 - 7M",
  distancias: "T - 1,5T - ST - T - T - ST - T",
  triades: "I(##3, #5) - II - III - #IVº - Vº - VIm(#5) - VIIm",
  tetrades: "I7M(##3, #5) - II7 - III7 - #IVø - Vº(7M) - VIm(7M, #5) - VIIm7",
  notas: (
    [*C*],
    [C - D - E\# - F\# - G\# - A - B],
    [*Db*],
    [Db - Eb - F\# - G - A - Bb - C],
    [*D*],
    [D - E - F\#\# - G\# - A\# - B - C\#],
    [*Eb*],
    [Eb - F - G\# - A - B - C - D],
    [*E*],
    [E - F\# - G\#\# - A\# - B\# - C\# - D\#],
    [*F*],
    [F - G - A\# - B - C\# - D - E],
    [*F\#*],
    [F\# - G\# - A\#\# - B\# - C\#\# - D\# - E\#],
    [*G*],
    [G - A - B\# - C\# - D\# - E - F\#],
    [*Ab*],
    [Ab - Bb - C\# - D - E - F - G],
    [*A*],
    [A - B - C\#\# - D\# - E\# - F\# - G\#],
    [*Bb*],
    [Bb - C - D\# - E - F\# - G - A],
    [*B*],
    [B - C\# - D\#\# - E\# - F\#\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "Persa",
  subtitulo: "I7M(b5) da escala Persa",
  intervalos: "T - b2 - 3 - 4 - b5 - b6 - 7M",
  distancias: "ST - 1,5T - ST - ST - T - 1,5T - ST",
  triades: "I(b5) - bII - III(bb3) - IVm - bV(##3) - bVI+ - VIIº(bb3)",
  tetrades: "I7M(b5) - bII7M - III7M(bb3) - IVm(7M) - bV7M(##3) - bVI7M(#5) - VIIº7(bb3)",
  notas: (
    [*C*],
    [C - Db - E - F - Gb - Ab - B],
    [*Db*],
    [Db - Ebb - F - Gb - Abb - Bbb - C],
    [*D*],
    [D - Eb - F\# - G - Ab - Bb - C\#],
    [*Eb*],
    [Eb - Fb - G - Ab - Bbb - Cb - D],
    [*E*],
    [E - F - G\# - A - Bb - C - D\#],
    [*F*],
    [F - Gb - A - Bb - Cb - Db - E],
    [*F\#*],
    [F\# - G - A\# - B - C - D - E\#],
    [*G*],
    [G - Ab - B - C - Db - Eb - F\#],
    [*Ab*],
    [Ab - Bbb - C - Db - Ebb - Fb - G],
    [*A*],
    [A - Bb - C\# - D - Eb - F - G\#],
    [*Bb*],
    [Bb - Cb - D - Eb - Fb - Gb - A],
    [*B*],
    [B - C - D\# - E - F - G - A\#],
  ),
)

#render-modo(
  nome: "2 Persa",
  subtitulo: "bII7M da escala Persa",
  intervalos: "T - #2 - 3 - 4 - 5 - 6 - 7M",
  distancias: "1,5T - ST - ST - T - 1,5T - ST - ST",
  triades: "I - II(bb3) - IIIm - IV(##3) - V+ - #VIº(bb3) - VII(b5)",
  tetrades: "I7M - II7M(bb3) - IIIm(7M) - IV7M(##3) - V7M(#5) - #VIº7(bb3) - VII7M(b5)",
  notas: (
    [*C*],
    [C - D\# - E - F - G - A - B],
    [*Db*],
    [Db - E - F - Gb - Ab - Bb - C],
    [*D*],
    [D - E\# - F\# - G - A - B - C\#],
    [*Eb*],
    [Eb - F\# - G - Ab - Bb - C - D],
    [*E*],
    [E - F\#\# - G\# - A - B - C\# - D\#],
    [*F*],
    [F - G\# - A - Bb - C - D - E],
    [*F\#*],
    [F\# - G\#\# - A\# - B - C\# - D\# - E\#],
    [*G*],
    [G - A\# - B - C - D - E - F\#],
    [*Ab*],
    [Ab - B - C - Db - Eb - F - G],
    [*A*],
    [A - B\# - C\# - D - E - F\# - G\#],
    [*Bb*],
    [Bb - C\# - D - Eb - F - G - A],
    [*B*],
    [B - C\#\# - D\# - E - F\# - G\# - A\#],
  ),
)

#render-modo(
  nome: "3 Persa",
  subtitulo: "III7M(bb3) da escala Persa",
  intervalos: "T - b2 - bb3 - b4 - 5 - b6 - bb7",
  distancias: "ST - ST - T - 1,5T - ST - ST - 1,5T",
  triades: "I(bb3) - bIIm - bIII(##3) - bIV+ - Vº(bb3) - bVI(b5) - bbVII",
  tetrades: "I7M(bb3) - bIIm(7M) - bIII7M(##3) - bIV7M(#5) - Vº7(bb3) - bVI7M(b5) - bbVII7",
  notas: (
    [*C*],
    [C - Db - Ebb - Fb - G - Ab - Bbb],
    [*C\#*],
    [C\# - D - Eb - F - G\# - A - Bb],
    [*D*],
    [D - Eb - Fb - Gb - A - Bb - Cb],
    [*D\#*],
    [D\# - E - F - G - A\# - B - C],
    [*E*],
    [E - F - Gb - Ab - B - C - Db],
    [*F*],
    [F - Gb - Abb - Bbb - C - Db - Ebb],
    [*F\#*],
    [F\# - G - Ab - Bb - C\# - D - Eb],
    [*G*],
    [G - Ab - Bbb - Cb - D - Eb - Fb],
    [*G\#*],
    [G\# - A - Bb - C - D\# - E - F],
    [*A*],
    [A - Bb - Cb - Db - E - F - Gb],
    [*A\#*],
    [A\# - B - C - D - E\# - F\# - G],
    [*B*],
    [B - C - Db - Eb - F\# - G - Ab],
  ),
)

#render-modo(
  nome: "4 Persa",
  subtitulo: "IVm(7M) da escala Persa",
  intervalos: "T - b2 - b3 - #4 - 5 - b6 - 7M",
  distancias: "ST - T - 1,5T - ST - ST - 1,5T - ST",
  triades: "Im - bII(##3) - bIII+ - #IVº(bb3) - V(b5) - bVI - VII(bb3)",
  tetrades: "Im(7M) - bII7M(##3) - bIII7M(#5) - #IVº7(bb3) - V7M(b5) - bVI7M - VII7M(bb3)",
  notas: (
    [*C*],
    [C - Db - Eb - F\# - G - Ab - B],
    [*C\#*],
    [C\# - D - E - F\#\# - G\# - A - B\#],
    [*D*],
    [D - Eb - F - G\# - A - Bb - C\#],
    [*Eb*],
    [Eb - Fb - Gb - A - Bb - Cb - D],
    [*E*],
    [E - F - G - A\# - B - C - D\#],
    [*F*],
    [F - Gb - Ab - B - C - Db - E],
    [*F\#*],
    [F\# - G - A - B\# - C\# - D - E\#],
    [*G*],
    [G - Ab - Bb - C\# - D - Eb - F\#],
    [*Ab*],
    [Ab - Bbb - Cb - D - Eb - Fb - G],
    [*A*],
    [A - Bb - C - D\# - E - F - G\#],
    [*Bb*],
    [Bb - Cb - Db - E - F - Gb - A],
    [*B*],
    [B - C - D - E\# - F\# - G - A\#],
  ),
)

#render-modo(
  nome: "5 Persa",
  subtitulo: "bV7M(##3) da escala Persa",
  intervalos: "T - 2 - #3 - #4 - 5 - b7 - 7M",
  distancias: "T - 1,5T - ST - ST - 1,5T - ST - ST",
  triades: "I(##3) - II+ - IIIº(bb3) - #IV(b5) - V - bVIIm(bb7) - VII",
  tetrades: "I7M(##3) - II7M(#5) - IIIº7(bb3) - #IV7(b5) - V7 - bVIIm(b7) - VII7M",
  notas: (
    [*C*],
    [C - D - E\# - F\# - G - Bb - B],
    [*Db*],
    [Db - Eb - F\# - G - Ab - Cb - C],
    [*D*],
    [D - E - F\#\# - G\# - A - C - C\#],
    [*Eb*],
    [Eb - F - G\# - A - Bb - Db - D],
    [*E*],
    [E - F\# - G\#\# - A\# - B - D - D\#],
    [*F*],
    [F - G - A\# - B - C - Eb - E],
    [*F\#*],
    [F\# - G\# - A\#\# - B\# - C\# - E - E\#],
    [*G*],
    [G - A - B\# - C\# - D - F - F\#],
    [*Ab*],
    [Ab - Bb - C\# - D - Eb - Gb - G],
    [*A*],
    [A - B - C\#\# - D\# - E - G - G\#],
    [*Bb*],
    [Bb - C - D\# - E - F - Ab - A],
    [*B*],
    [B - C\# - D\#\# - E\# - F\# - A - A\#],
  ),
)

#render-modo(
  nome: "6 Persa",
  subtitulo: "bVI7M(#5) da escala Persa",
  intervalos: "T - #2 - 3 - 4 - #5 - 6 - 7",
  distancias: "1,5T - ST - ST - 1,5T - ST - ST - T",
  triades: "I+ - #IIº(bb3) - III(b5) - IV - #Vm - VIm(bb7) - bVII",
  tetrades: "I7(#5) - #IIº7(bb3) - III7(b5) - IV7 - #Vm7 - VIm(b7) - bVII7",
  notas: (
    [*C*],
    [C - D\# - E - F - G\# - A - Bb],
    [*Db*],
    [Db - E - F - Gb - A - Bb - Cb],
    [*D*],
    [D - E\# - F\# - G - A\# - B - C],
    [*Eb*],
    [Eb - F\# - G - Ab - B - C - Db],
    [*E*],
    [E - F\#\# - G\# - A - B\# - C\# - D],
    [*F*],
    [F - G\# - A - Bb - C\# - D - Eb],
    [*F\#*],
    [F\# - G\#\# - A\# - B - C\#\# - D\# - E],
    [*G*],
    [G - A\# - B - C - D\# - E - F],
    [*Ab*],
    [Ab - B - C - Db - E - F - Gb],
    [*A*],
    [A - B\# - C\# - D - E\# - F\# - G],
    [*Bb*],
    [Bb - C\# - D - Eb - F\# - G - Ab],
    [*B*],
    [B - C\#\# - D\# - E - F\#\# - G\# - A],
  ),
)

#render-modo(
  nome: "7 Persa",
  subtitulo: "VIIº7(bb3) da escala Persa",
  intervalos: "T - b2 - bb3 - 4 - b5 - bb6 - bb7",
  distancias: "ST - ST - 1,5T - ST - ST - T - 1,5T",
  triades: "Iº(bb3) - bIIm(b5) - bbIII - bIVm - bVm(bb7) - bbVI - bbVII+",
  tetrades: "Iº7(bb3) - bIIm7(b5) - bbIII7 - bIVm7 - bVm(b7) - bbVI7 - bbVII7M(#5)",
  notas: (
    [*C*],
    [C - Db - Ebb - F - Gb - Abb - Bbb],
    [*C\#*],
    [C\# - D - Eb - F\# - G - Ab - Bb],
    [*D*],
    [D - Eb - Fb - G - Ab - Bbb - Cb],
    [*D\#*],
    [D\# - E - F - G\# - A - Bb - C],
    [*E*],
    [E - F - Gb - A - Bb - Cb - Db],
    [*F*],
    [F - Gb - Abb - Bb - Cb - Dbb - Ebb],
    [*F\#*],
    [F\# - G - Ab - B - C - Db - Eb],
    [*G*],
    [G - Ab - Bbb - C - Db - Ebb - Fb],
    [*G\#*],
    [G\# - A - Bb - C\# - D - Eb - F],
    [*A*],
    [A - Bb - Cb - D - Eb - Fb - Gb],
    [*A\#*],
    [A\# - B - C - D\# - E - F - G],
    [*B*],
    [B - C - Db - E - F - Gb - Ab],
  ),
)

#render-modo(
  nome: "Enigmática",
  subtitulo: "I+ da escala Enigmática",
  intervalos: "T - b2 - 3 - #4 - #5 - #6 - 7M",
  distancias: "ST - 1,5T - T - T - T - ST - ST",
  triades: "I+ - bII(##3, #5) - III - #IV(b5) - #V(bb3) - #VIº(bb3) - VII",
  tetrades: "I7M(#5) - bII7M(##3, #5) - III7M - #IV7(b5) - #V7(bb3) - #VIº7(bb3) - VII7M",
  notas: (
    [*C*],
    [C - Db - E - F\# - G\# - A\# - B],
    [*Db*],
    [Db - Ebb - F - G - A - B - C],
    [*D*],
    [D - Eb - F\# - G\# - A\# - B\# - C\#],
    [*Eb*],
    [Eb - Fb - G - A - B - C\# - D],
    [*E*],
    [E - F - G\# - A\# - B\# - C\#\# - D\#],
    [*F*],
    [F - Gb - A - B - C\# - D\# - E],
    [*F\#*],
    [F\# - G - A\# - B\# - C\#\# - D\#\# - E\#],
    [*G*],
    [G - Ab - B - C\# - D\# - E\# - F\#],
    [*Ab*],
    [Ab - Bbb - C - D - E - F\# - G],
    [*A*],
    [A - Bb - C\# - D\# - E\# - F\#\# - G\#],
    [*Bb*],
    [Bb - Cb - D - E - F\# - G\# - A],
    [*B*],
    [B - C - D\# - E\# - F\#\# - G\#\# - A\#],
  ),
)

#render-modo(
  nome: "2 Enigmática",
  subtitulo: "bII7M(##3, #5) da escala Enigmática",
  intervalos: "T - #2 - 4 - 5 - 6 - 7 - 7M",
  distancias: "1,5T - T - T - T - ST - ST - ST",
  triades: "I(##3, #5) - #II - III(b5) - IV(bb3) - Vº(bb3) - VI - #VI",
  tetrades: "I7M(##3, #5) - #II7M - III7(b5) - IV7(bb3) - Vº7(bb3) - VI7M - #VI7M",
  notas: (
    [*C*],
    [C - D\# - F - G - A - Bb - B],
    [*Db*],
    [Db - E - Gb - Ab - Bb - Cb - C],
    [*D*],
    [D - E\# - G - A - B - C - C\#],
    [*Eb*],
    [Eb - F\# - Ab - Bb - C - Db - D],
    [*E*],
    [E - F\#\# - A - B - C\# - D - D\#],
    [*F*],
    [F - G\# - Bb - C - D - Eb - E],
    [*F\#*],
    [F\# - G\#\# - B - C\# - D\# - E - E\#],
    [*G*],
    [G - A\# - C - D - E - F - F\#],
    [*Ab*],
    [Ab - B - Db - Eb - F - Gb - G],
    [*A*],
    [A - B\# - D - E - F\# - G - G\#],
    [*Bb*],
    [Bb - C\# - Eb - F - G - Ab - A],
    [*B*],
    [B - C\#\# - E - F\# - G\# - A - A\#],
  ),
)

#render-modo(
  nome: "3 Enigmática",
  subtitulo: "III7M da escala Enigmática",
  intervalos: "T - 2 - 3 - #4 - 5 - b6 - bb7",
  distancias: "T - T - T - ST - ST - ST - 1,5T",
  triades: "I - II(b5) - III(bb3) - #IVº(bb3) - V - bVI - bVII(##3, #5)",
  tetrades: "I7 - II7(b5) - III7(bb3) - #IVº7(bb3) - V7M - bVI7M - bVII7M(##3, #5)",
  notas: (
    [*C*],
    [C - D - E - F\# - G - Ab - Bbb],
    [*Db*],
    [Db - Eb - F - G - Ab - Bbb - Cbb],
    [*D*],
    [D - E - F\# - G\# - A - Bb - Cb],
    [*Eb*],
    [Eb - F - G - A - Bb - Cb - Dbb],
    [*E*],
    [E - F\# - G\# - A\# - B - C - Db],
    [*F*],
    [F - G - A - B - C - Db - Ebb],
    [*F\#*],
    [F\# - G\# - A\# - B\# - C\# - D - Eb],
    [*G*],
    [G - A - B - C\# - D - Eb - Fb],
    [*Ab*],
    [Ab - Bb - C - D - Eb - Fb - Gbb],
    [*A*],
    [A - B - C\# - D\# - E - F - Gb],
    [*Bb*],
    [Bb - C - D - E - F - Gb - Abb],
    [*B*],
    [B - C\# - D\# - E\# - F\# - G - Ab],
  ),
)

#render-modo(
  nome: "4 Enigmática",
  subtitulo: "#IV7(b5) da escala Enigmática",
  intervalos: "T - 2 - 3 - 4 - b5 - bb6 - b7",
  distancias: "T - T - ST - ST - ST - 1,5T - T",
  triades: "I(b5) - II(bb3) - IIIº(bb3) - IV - bV - bVI(##3, #5) - bVII",
  tetrades: "I7(b5) - II7(bb3) - IIIº7(bb3) - IV7M - bV7M - bVI7M(##3, #5) - bVII7",
  notas: (
    [*C*],
    [C - D - E - F - Gb - Abb - Bb],
    [*Db*],
    [Db - Eb - F - Gb - Abb - Bbb - Cb],
    [*D*],
    [D - E - F\# - G - Ab - Bbb - C],
    [*Eb*],
    [Eb - F - G - Ab - Bbb - Cbb - Db],
    [*E*],
    [E - F\# - G\# - A - Bb - Cb - D],
    [*F*],
    [F - G - A - Bb - Cb - Dbb - Eb],
    [*F\#*],
    [F\# - G\# - A\# - B - C - Db - E],
    [*G*],
    [G - A - B - C - Db - Ebb - F],
    [*Ab*],
    [Ab - Bb - C - Db - Ebb - Fbb - Gb],
    [*A*],
    [A - B - C\# - D - Eb - Fb - G],
    [*Bb*],
    [Bb - C - D - Eb - Fb - Gbb - Ab],
    [*B*],
    [B - C\# - D\# - E - F - Gb - A],
  ),
)

#render-modo(
  nome: "5 Enigmática",
  subtitulo: "#V7(bb3) da escala Enigmática",
  intervalos: "T - 2 - b3 - b4 - bb5 - b6 - b7",
  distancias: "T - ST - ST - ST - 1,5T - T - T",
  triades: "I(bb3) - IIm(bb5) - bIII - bIV - bV(##3, #5) - bVI - bVII(b5)",
  tetrades: "I7(bb3) - IIm7(bb5) - bIII7M - bIV7M - bV7M(##3, #5) - bVI7 - bVII7(b5)",
  notas: (
    [*C*],
    [C - D - Eb - Fb - Gbb - Ab - Bb],
    [*C\#*],
    [C\# - D\# - E - F - G - A - B],
    [*D*],
    [D - E - F - Gb - Abb - Bb - C],
    [*Eb*],
    [Eb - F - Gb - Abb - Bbb - Cb - Db],
    [*E*],
    [E - F\# - G - Ab - Bbb - C - D],
    [*F*],
    [F - G - Ab - Bbb - Cbb - Db - Eb],
    [*F\#*],
    [F\# - G\# - A - Bb - C - D - E],
    [*G*],
    [G - A - Bb - Cb - Dbb - Eb - F],
    [*G\#*],
    [G\# - A\# - B - C - D - E - F\#],
    [*A*],
    [A - B - C - Db - Ebb - F - G],
    [*Bb*],
    [Bb - C - Db - Ebb - Fbb - Gb - Ab],
    [*B*],
    [B - C\# - D - Eb - Fb - G - A],
  ),
)

#render-modo(
  nome: "6 Enigmática",
  subtitulo: "#VIº7(bb3) da escala Enigmática",
  intervalos: "T - b2 - bb3 - bb4 - b5 - b6 - b7",
  distancias: "ST - ST - ST - 1,5T - T - T - T",
  triades: "Iº(bb3) - bII - bbIII - bbIV(##3, #5) - bV - bVIm - bbVII(b5)",
  tetrades: "Iº7(bb3) - bII7M - bbIII7M - bbIV7M(##3, #5) - bV7 - bVIm7 - bbVII7(b5)",
  notas: (
    [*C*],
    [C - Db - Ebb - Fbb - Gb - Ab - Bb],
    [*C\#*],
    [C\# - D - Eb - Fb - G - A - B],
    [*D*],
    [D - Eb - Fb - Gbb - Ab - Bb - C],
    [*D\#*],
    [D\# - E - F - Gb - A - B - C\#],
    [*E*],
    [E - F - Gb - Abb - Bb - C - D],
    [*F*],
    [F - Gb - Abb - Bbb - Cb - Db - Eb],
    [*F\#*],
    [F\# - G - Ab - Bbb - C - D - E],
    [*G*],
    [G - Ab - Bbb - Cbb - Db - Eb - F],
    [*G\#*],
    [G\# - A - Bb - Cb - D - E - F\#],
    [*A*],
    [A - Bb - Cb - Dbb - Eb - F - G],
    [*A\#*],
    [A\# - B - C - Db - E - F\# - G\#],
    [*B*],
    [B - C - Db - Ebb - F - G - A],
  ),
)

#render-modo(
  nome: "7 Enigmática",
  subtitulo: "VII7M da escala Enigmática",
  intervalos: "T - b2 - bb3 - 4 - 5 - 6 - 7M",
  distancias: "ST - ST - 1,5T - T - T - T - ST",
  triades: "I - bII - bbIII(##3, #5) - IV - Vm - VI(b5) - bVII(bb3)",
  tetrades: "I7M - bII7M - bbIII7M(##3, #5) - IV7 - Vm7 - VI7(b5) - bVII7(bb3)",
  notas: (
    [*C*],
    [C - Db - Ebb - F - G - A - B],
    [*C\#*],
    [C\# - D - Eb - F\# - G\# - A\# - B\#],
    [*D*],
    [D - Eb - Fb - G - A - B - C\#],
    [*D\#*],
    [D\# - E - F - G\# - A\# - B\# - C\#\#],
    [*E*],
    [E - F - Gb - A - B - C\# - D\#],
    [*F*],
    [F - Gb - Abb - Bb - C - D - E],
    [*F\#*],
    [F\# - G - Ab - B - C\# - D\# - E\#],
    [*G*],
    [G - Ab - Bbb - C - D - E - F\#],
    [*G\#*],
    [G\# - A - Bb - C\# - D\# - E\# - F\#\#],
    [*A*],
    [A - Bb - Cb - D - E - F\# - G\#],
    [*Bb*],
    [Bb - Cb - Dbb - Eb - F - G - A],
    [*B*],
    [B - C - Db - E - F\# - G\# - A\#],
  ),
  ultimo: true,
)
